headers = ["Area", "NPC", "XP", "Gold Carried", "Pickpocket Skill", "Item Price (base)", "Item Type", "Item"]

areas = [
	"ar0020 - City Gates",
	"ar0021 - Crooked Crane 1st Floor",
	"ar0028 - Candlekeep Dream (After PC Soultheft)",
	"ar0071 - Spellhold (Imoen Soultheft Cutscene -- 'Silence do, you have no purpose...')",
	"ar0072 - Ust Natha Temple (Irenicus/Bodhi, Ardula/Phaere Cutscene)",
	"ar0082 - Lich Grave in Bridge District Inn",
	"ar0202 - The Unseeing Eye Cult Hideout",
	"ar0206 - Ghoul village (Temple District)",
	"ar0300 - The Docks",
	"ar0301 - Mae'Var's Hide Out",
	"ar0302 - Mae'Var's Inn 1st Floor -- Entrance",
	"ar0303 - Mae'Var's Inn 2nd Floor -- Training Area",
	"ar0305 - Shadow Thieves Guild Entrance",
	"ar0306 - Renal Bloodscalp's Hideout",
	"ar0307 - aran Linvail's Hideout",
	"ar0308 - Harper's 1st Floor",
	"ar0312 - Sleeping Room (Entry point down) -- Arledrian",
	"ar0313 - Sea Bounty Tavern 1st Floor",
	"ar0314 - Sea Bounty Tavern 2nd Floor",
	"ar0317 - Sleeping Room (Favour for Edwin -- Mae'Var Plot)",
	"ar0319 - Temple of Oghma",
	"ar0322 - Thief Stronghold (1st Floor)",
	"ar0329 - aran's Hideout (sided with Bodhi)",
	"ar0332 - Barracks in the Docks",
	"ar0333 - Barracks in the Docks",
	"ar0400 - Slums",
	"ar0401 - Jansen Cellar",
	"ar0402 - Jansen 1st Floor",
	"ar0404 - Sewers beneath Coronet -- Lilarcor",
	"ar0405 - Slaver's Ship Building",
	"ar0406 - Copper Coronet",
	"ar0407 - Prebek's House",
	"ar0408 - Temple of Ilmater",
	"ar0410 - Sphere: Navigator's room -- Lavok's Hideout",
	"ar0411 - Sphere: Entrance floor",
	"ar0412 - Sphere: Ice and Fire Room",
	"ar0414 - Sphere: Demon Plane",
	"ar0418 - Myconids",
	"ar0500 - Bridge District",
	"ar0504 - Saerk's House 1st Floor",
	"ar0505 - Saerk's House 2nd Floor",
	"ar0506 - Noble House 1st Floor",
	"ar0507 - Kidnappers' Hideout 1st Floor",
	"ar0509 - Five Flagons Inn 1st Floor",
	"ar0510 - Five Flagons Inn Theater",
	"ar0511 - Five Flagons Inn 2nd Floor",
	"ar0512 - Temple of Helm",
	"ar0513 - Calbor's Inn at Bridge District 1st Floor",
	"ar0514 - Inn at Bridge District 2nd Floor",
	"ar0515 - Inn at Bridge District 3rd Floor",
	"ar0516 - Planar Prison",
	"ar0522 - Five Flagons Inn (Stronghold)",
	"ar0602 - Irenicus's Dungeon 1st Floor",
	"ar0603 - Irenicus's Dungeon 2nd Floor",
	"ar0604 - Circus Tent 1st Floor",
	"ar0606 - Circus Tent 3rd Floor",
	"ar0700 - Waukeen's Promenade",
	"ar0701 - The Sewers",
	"ar0702 - Adventurer's Mart",
	"ar0704 - Mithrest Inn",
	"ar0705 - Mekrath's Hideout in the Sewers (Haer'Dalis Plot)",
	"ar0706 - armourer/Fletcher",
	"ar0709 - Den of the Seven Vales 1st Floor",
	"ar0712 - Den of the Seven Vales 2nd Floor",
	"ar0713 - Store or Inn at Promenade",
	"ar0800 - Graveyard",
	"ar0804 - Pai'Na's Hideout",
	"ar0806 - Crypt",
	"ar0808 - Bodhi's Hideout (Abduction Plot, getting Imoen's soul)",
	"ar0900 - Temple District",
	"ar0901 - Temple of Helm",
	"ar0902 - Temple of Lathander",
	"ar0903 - Order of the Radiant Heart",
	"ar0904 - Temple of Talos",
	"ar0905 - Pimlico's Estate",
	"ar1000 - Government District",
	"ar1001 - Delryn's Estate",
	"ar1002 - Councel Building",
	"ar1003 - Firecam's Estate",
	"ar1005 - Prison",
	"ar1006 - Jysstev's Estate (Oisig Plot)",
	"ar1010 - Temple of Waukeen",
	"ar1100 - Umar Hills",
	"ar1103 - Jermien's Cabin",
	"ar1105 - Imnesvale Inn",
	"ar1200 - Windspear Hills",
	"ar1201 - Firkraag's Entrance",
	"ar1202 - Firkraag's Maze",
	"ar1203 - Firkraag's Hideout",
	"ar1300 - De'Arnise Keep Destroyed",
	"ar1301 - De'Arnise Cellar",
	"ar1303 - De'Arnise Keep 2nd Floor (Destroyed)",
	"ar1304 - De'Arnise Keep (Restored, Stronghold)",
	"ar1306 - De'Arnise Keep (Stronghold)",
	"ar1400 - Shadow Temple Land (restored, Ranger)",
	"ar1401 - Shadow Temple",
	"ar1404 - Shadow Temple Land shadowed",
	"ar1600 - Brynnlaw",
	"ar1602 - Brynnlaw's Inn",
	"ar1605 - CW's House",
	"ar1607 - Githyanki Assault",
	"ar1610 - Brothel Prison",
	"ar1611 - Brothel",
	"ar1612 - Brothel Kitchen",
	"ar1800 - North Forest",
	"ar1900 - Druid Grove Area",
	"ar1901 - Druid Grove",
	"ar1902 - Storehouse (Ihtafeer's Storehouse)",
	"ar2000 - Trademeet",
	"ar2002 - Fentan's House",
	"ar2007 - High Merchant's Estate",
	"ar2008 - Temple of Waukeen",
	"ar2010 - Trademeet's Inn",
	"ar2011 - Alibakkar's Estate",
	"ar2012 - Lurraxol's Estate",
	"ar2017 - Courtesan Tent",
	"ar2100 - Underdark",
	"ar2200 - Ust Natha",
	"ar2201 - Temple in Ust Natha",
	"ar2202 - Inn in Ust Natha 1st Floor",
	"ar2203 - Inn in Ust Natha; 2nd Floor",
	"ar2206 - Qilue's House in Ust Natha",
	"ar2207 - Deirex's Tower in Ust Natha",
	"ar2208 - Jarlaxle's House wherever",
	"ar2209 - Jae'llat's House",
	"ar2300 - Sahuagin City",
	"ar2401 - Cave Between Underdark and Exit from Underdark",
	"ar2402 - Kuo Toa in Underdark",
	"ar2600 - Thetyr Wood",
	"ar2800 - Suldanessellar",
	"ar2801 - House of High Priestess of Suldanessellar",
	"ar2806 - Tree of Life",
	"ar2903 - Greed (Abyss)",
	"ar2904 - Selfish (Abyss)",
	"ar3000",
	"ar3001",
	"ar3005",
	"ar3006",
	"ar3012",
	"ar3013",
	"ar3015",
	"ar3016",
	"ar5000",
	"ar5002",
	"ar5003",
	"ar5004",
	"ar5007",
	"ar5013",
	"ar5014",
	"ar5016",
	"ar5200",
	"ar5202",
	"ar5500",
	"ar5501",
	"ar5502",
	"ar5504",
	"ar5506",
	"ar5508",
	"ar6000",
	"ar6001",
	"ar6002",
	"ar6003",
	"ar6100",
	"ar6102",
	"ar6106",
	"ar6108",
	"ar6300",
	"ar6400",
	"bd0010 - Ducal Palace City Exterior",
	"bd0020 - Sorcerous/Elf Song City Exterior",
	"bd0021",
	"bd0030 - Flaming Fist City Exterior",
	"bd0035",
	"bd0040 - Three Kegs City Exterior",
	"bd0050 - Iron Throne City Exterior",
	"bd0064 - Random Area - Forest Paths",
	"bd0100 - Ducal Palace  Second Floor",
	"bd0101 - Ducal Palace  Leaving BG",
	"bd0102 - Ducal Palace  First Floor",
	"bd0103 - Ducal Palace  Third Floor",
	"bd0104 - Flaming Fist HQ",
	"bd0106 - Three Old Kegs  First Floor",
	"bd0107 - Three Old Kegs  Second Floor",
	"bd0108 - Three Old Kegs  Third Floor",
	"bd0109 - Elfsong Tavern  First Floor",
	"bd0110 - Elfsong Tavern  Second Floor",
	"bd0111 - Iron Throne Floor  First Floor",
	"bd0112 - Baldur s Gate East",
	"bd0120 - Tomb Safehouse  First Floor",
	"bd0130 - Tomb Safehouse  Second Floor",
	"bd1000 - Coast Way Crossing",
	"bd1100 - The Dig",
	"bd1200 - Lich Outpost",
	"bd2000 - Boareskyr Bridge & Bridgefort",
	"bd2100 - Bridgefort Interior",
	"bd3000 - Allied Siege Camp",
	"bd4000 - Dragonspear Castle  Exterior",
	"bd4100 - Dragonspear Castle Keep  First Floor",
	"bd4300 - Dragonspear Castle Basement",
	"bd4400 - Avernus",
	"bd4700 - Avernus Roof",
	"bd5000 - Underground River Entrance",
	"bd5100 - Underground River",
	"bd5200 - The Warrens",
	"bd5300 - Kanaglym",
	"bd7000 - Coast Way Forest",
	"bd7100 - Troll Forest",
	"bd7200 - Forest of Wyrms",
	"bd7230 - Temple of Cyric",
	"bd7300 - Dead Man s Pass",
	"bd7400 - Bloodbark Grove",
	"bg0004 - N Baldur's Gate: Bheren's House L1",
	"bg0006 - N Baldur's Gate: Rinnie's House L1",
	"bg0010 - N Baldur's Gate: Jardak's House L1",
	"bg0011 - N Baldur's Gate: Jardak's House L2",
	"bg0102 - NW Baldur's Gate: Silvershield Estate L2",
	"bg0105 - SE Baldur's Gate: Blade & Stars L1",
	"bg0112 - Baldur's Gate Undercellars",
	"bg0114 - NE Baldur's Gate: Blushing Mermaid L1",
	"bg0116 - NW Baldur's Gate: Helm & Cloak L1",
	"bg0119 - N Baldur's Gate: Three Old Kegs L1",
	"bg0120 - N Baldur's Gate: Three Old Kegs L2",
	"bg0121 - N Baldur's Gate: Three Old Kegs L3",
	"bg0123 - Undercity",
	"bg0125 - Undercity: Temple of Bhaal",
	"bg0126 - W Baldur's Gate: Ragefast's House",
	"bg0128 - SW Baldur's Gate: Merchant League L2",
	"bg0130 - W Baldur's Gate: Hall of Wonders",
	"bg0131 - W Baldur's Gate: High House of Wonders",
	"bg0132 - W Baldur's Gate: Lady's House",
	"bg0134 - Baldur's Gate Docks: Low Lantern D2",
	"bg0135 - Baldur's Gate Docks: Low Lantern D3",
	"bg0143 - Central Baldur's Gate: Oberon's Estate L1",
	"bg0145 - Central Baldur's Gate: Oberon's Estate L3",
	"bg0153 - E Baldur's Gate: Thieves' Guild",
	"bg0162 - NW Baldur's Gate: Laerta's House L1",
	"bg0167 - NW Baldur's Gate: Pheirkas' House L1",
	"bg0200 - N Baldur's Gate",
	"bg0224 - W Sewers",
	"bg0225 - Central Sewers",
	"bg0226 - E Sewers",
	"bg0300 - NE Baldur's Gate",
	"bg0307 - NE Baldur's Gate: Counting House L1",
	"bg0501 - Durlag's Tower: Cellar",
	"bg0504 - Durlag's Tower: L3",
	"bg0505 - Durlag's Tower: L4",
	"bg0514 - Durlag's Tower: D4",
	"bg0516 - Durlag's Tower: Demonknight's Chamber",
	"bg0601 - SW Baldur's Gate: Seven Suns L1",
	"bg0602 - SW Baldur's Gate: Seven Suns L2",
	"bg0612 - Baldur's Gate Docks: Iron Throne L2",
	"bg0613 - Baldur's Gate Docks: Iron Throne L3",
	"bg0615 - Baldur's Gate Docks: Iron Throne L5",
	"bg0703 - E Baldur's Gate: Sorcerous Sundries L1",
	"bg0704 - E Baldur's Gate: Sorcerous Sundries L2",
	"bg0705 - E Baldur's Gate: Elfsong Tavern L1",
	"bg0706 - E Baldur's Gate: Elfsong Tavern L2",
	"bg0715 - Central Baldur's Gate: Nadine's House L1",
	"bg0800 - E Baldur's Gate",
	"bg0805 - E Baldur's Gate: Arkion's House L1",
	"bg0813 - SE Baldur's Gate: Nemphre's House L1",
	"bg0900 - Wyrm's Crossing",
	"bg1000 - Ulgoth's Beard",
	"bg1001 - Ulgoth's Beard: Inn",
	"bg1005 - Ulgoth's Beard: Therella's House",
	"bg1009 - Ice Island: Maze L1",
	"bg1010 - Ice Island: Maze L2",
	"bg1101 - SW Baldur's Gate: Wiven's House L1",
	"bg1111 - SW Baldur's Gate: Sunin's House",
	"bg1200 - Baldur's Gate Docks",
	"bg1208 - Baldur's Gate Docks: Noralee's Warehouse",
	"bg1209 - Baldur's Gate Docks: Larriaz' House L1",
	"bg1213 - Baldur's Gate Docks: Cordyr's House L1",
	"bg1303 - SE Baldur's Gate: Nadarin's Warehouse",
	"bg1316 - SE Baldur's Gate: Taxek's House L1",
	"bg1400 - Lower Chionthar",
	"bg1500 - Balduran's Isle (North)",
	"bg1504 - Balduran's Isle (North): Ship D4",
	"bg1600 - Cloakwood Grove",
	"bg1603 - Cloakwood Grove: Peter's Cave",
	"bg1800 - Cloakwood Mines",
	"bg1802 - Cloakwood Mines: L3",
	"bg1803 - Cloakwood Mines: L4",
	"bg1900 - Bandit Camp",
	"bg1901 - Bandit Camp: Raemon's Tent",
	"bg1902 - Bandit Camp: Tent2",
	"bg1903 - Bandit Camp: Gnoll Cave",
	"bg1904 - Bandit Camp: Tersus' Tent",
	"bg1905 - Bandit Camp: Tent1",
	"bg2000 - Balduran's Isle (South)",
	"bg2101 - Cloakwood Falls: Spider Nest",
	"bg2200 - Cloakwood Lodge",
	"bg2300 - Friendly Arm Inn",
	"bg2302 - Friendly Arm Inn: L2",
	"bg2303 - Friendly Arm Inn: L3",
	"bg2304 - Friendly Arm Inn: Temple of Wisdom",
	"bg2400 - Peldvale",
	"bg2600 - Candlekeep",
	"bg2602 - Candlekeep: Priest's Quarters",
	"bg2605 - Candlekeep: Infirmary",
	"bg2607 - Candlekeep: Bunkhouse",
	"bg2609 - Candlekeep: Library L2",
	"bg2610 - Candlekeep: Library L3",
	"bg2614 - Candlekeep: Library L6",
	"bg2615 - Candlekeep: Catacombs L1",
	"bg2618 - Candlekeep: Barracks",
	"bg2619 - Candlekeep: Catacombs L2",
	"bg2626 - Candlekeep: Ch.6",
	"bg2631 - Candlekeep: Ch.6 Barracks",
	"bg2639",
	"bg2800 - Coast Way",
	"bg2900 - Larswood",
	"bg3000 - Spider Wood",
	"bg3100 - Rocky Coast",
	"bg3200 - High Hedge",
	"bg3202 - High Hedge: Thalanthyr's Abode",
	"bg3300 - Beregost",
	"bg3304 - Beregost: Jovial Juggler L1",
	"bg3313 - Beregost: Mirianne's House L1",
	"bg3320 - Beregost: Travenhurst Manor L1",
	"bg3327 - Beregost: House14 L1",
	"bg3333 - Beregost: Firebead's House L1",
	"bg3351 - Beregost: Feldepost's Inn L1",
	"bg3352 - Beregost: Feldepost's Inn L2",
	"bg3357 - Beregost: Red Sheaf L1",
	"bg3400 - Temple of Lathander",
	"bg3402 - Temple of Lathander: Song of the Morning",
	"bg3500 - Sharp Teeth Plain",
	"bg3600 - Lighthouse",
	"bg3700 - Red Canyons",
	"bg3800 - Trade Way North",
	"bg3900 - Ulcaster",
	"bg4000 - Gullykin",
	"bg4003 - Gullykin: Winery L1",
	"bg4007 - Gullykin: House3 L1",
	"bg4011 - Gullykin: House5 L1",
	"bg4100 - Ancient Ruins",
	"bg4200 - Wilderness Lake",
	"bg4400 - Lonely Peaks",
	"bg4500 - Firewine Bridge",
	"bg4600 - Bear River",
	"bg4700 - Xvart Village",
	"bg4800 - Nashkel",
	"bg4801 - Nashkel: Inn",
	"bg4809 - Nashkel: Belching Dragon Tavern",
	"bg4810 - Nashkel: Garrison",
	"bg4900 - Nashkel Carnival",
	"bg4903 - Nashkel Carnival: Vitiare's Tent",
	"bg4905 - Nashkel Carnival: Potion Tent",
	"bg4906 - Nashkel Carnival: Zordral's Tent",
	"bg5000 - Valley of the Tombs",
	"bg5100 - Gnoll Stronghold",
	"bg5200 - Dryad Falls",
	"bg5201 - Firewine Ruins",
	"bg5300 - Fire Leaf Forest",
	"bg5400 - Nashkel Mines",
	"bg5401 - Nashkel Mines: L1",
	"bg5402 - Nashkel Mines: L2",
	"bg5405 - Nashkel Mines: Mulahey's Cave",
	"bg5500 - Gibberling Mountains",
	"bg5506 - Candlekeep Caves",
	"bg5710",
	"oh2000 - Adoy's Enclave",
	"oh2010",
	"oh3000 - Cloud Peaks",
	"oh3010",
	"oh3100",
	"oh4000 - Rasaad - The Amphitheater",
	"oh4010 - Rasaad - Tears of Selune battle encounter",
	"oh4100 - Rasaad - Dark Moon Heretic Temple",
	"oh4200",
	"oh4210",
	"oh4220",
	"oh5000 - Dorn - Radiant Heart (Wedding)",
	"oh5300 - Dorn - Helmite Camp",
	"oh5500",
	"oh6000 - Neera - The Wild Forest",
	"oh6100 - Neera - The Hidden Refuge",
	"oh6200 - Neera - The Hidden Refuge (Destroyed)",
	"oh6300 - Neera - Red Wizard Enclave",
	"oh6450",
	"oh6460",
	"oh6500",
	"oh7000 - Hexxat - Top Left Quarter (Dragomir)",
	"oh7100 - Hexxat - Bottom Left Quarter (Shou Lung)",
	"oh7200 - Hexxat - Bottom Right Quarter (Zakhara)",
	"oh7300",
	"oh8100 - TBP2 - Staging Area Map",
	"unknown",
]

types = {
	"Amulet": [
		"Amulet of Power",
		"Amulet of Protection +1",
		"Amulet of Spell Warding",
		"Amulet of the Keeper of Secrets Under the Mountain",
		"Arkion's Bloodstone Amulet",
		"Bloodstone Amulet",
		"Galvena's Medallion",
		"Gold Necklace",
		"Greenstone Amulet",
		"Keepsake Locket",
		"Laeral's Tear Necklace",
		"Lon's Amulet",
		"Necklace of Talos",
		"Pearl Necklace",
		"Periapt of Proof Against Poison",
		"Rainbow Obsidian Necklace",
		"Ruby Pendant of Beguiling",
		"Shield Amulet",
		"Sigil of Tyr",
		"Silver Necklace",
		"The Amplifier",
		"The One Gift Lost",
		"The Protector +1",
		"Thrall Collar",
	],
	"Armor": [
		"Adventurer's Robe",
		"Chain Mail Armor",
		"Leather Armor",
		"Leather Armor +1",
		"Leather Armor +3",
		"Skin of the Ghoul +4",
		"Studded Leather Armor",
	],
	"Arrows": [
		"Acid Arrow +1",
		"Arrow",
		"Arrow +1",
		"Arrow +2",
		"Arrow +3",
		"Arrow of Biting",
		"Arrow of Detonation",
		"Arrow of Dispelling",
		"Arrow of Fire",
		"Arrow of Ice",
		"Arrow of Piercing +1",
		"Flaming Arrow",
	],
	"Axe": [
		"Battle Axe",
		"Battle Axe +1",
		"Battle Axe +2",
		"Hangard's Axe +2",
		"Stonefire +3",
		"Throwing Axe",
		"Throwing Axe +2",
	],
	"Belt & Girdle": [
		"Adoy's Belt",
		"Belt of Antipode",
		"Belt of the Cunning Rogue",
		"Destroyer of the Hills",
		"Elves' Bane",
		"Girdle of Bluntness",
		"Girdle of Fortitude",
		"Girdle of Hill Giant Strength",
		"Girdle of Piercing",
		"Golden Girdle",
		"Golden Girdle of Urnst",
	],
	"Bolts": [
		"Bolt",
		"Bolt +1",
		"Bolt +2",
		"Bolt of Biting ",
		"Bolt of Lightning",
		"Case of Plenty +1",
		"Drow Bolt +1",
		"Drow Bolt of Sleep",
		"Drow Bolt of Stunning",
		"Flasher Master Bruiser Mate",
		"Kuo-toan Bolt",
		"Paralytic Bolt",
	],
	"Books & misc": [
		"Acorn of Yarrow",
		"Acorns",
		"Aerie's Body",
		"Ancient Armor",
		"Anomen's Body",
		"Barrel of Bwoosh!",
		"Bassilus's Holy Symbol",
		"Black Spider Figurine",
		"Book of Infinite Spells",
		"Bowl of Water Elemental Control",
		"Bowstring of Gond",
		"Demon Heart",
		"Dennis's Mother's Gong",
		"Draconis's Head",
		"Dradeel's Spellbook",
		"Edwin's Documents",
		"Efreeti Bottle",
		"Elven Holy Water",
		"Exotic Hide",
		"Farthing's Dolly",
		"Fil's Summoning Stone",
		"Flail Head (Acid)",
		"Gem of Seeing",
		"Ghost Jar",
		"Golden Goblet",
		"Golden Pantaloons",
		"Guril Berries",
		"Hindo's Hand",
		"Illithium Ore",
		"Ink and Sand",
		"Jae'llat Wardstone",
		"Jaheira's Body",
		"Journal of Umolex the Far-Eyed",
		"Keherrem's Badge",
		"Key to River Plug",
		"Light Gem",
		"Littleman the Stuffed Bear",
		"Magical Rope",
		"Meems's Special Grog",
		"Mekrath's Mirror",
		"Mug of Ale",
		"Mulahey's Holy Symbol",
		"Myconid Bloom-Sac",
		"Note",
		"Oak Bark",
		"Peladan",
		"Piece of Red Cloth",
		"Qilue's Brain",
		"Rebel's Orb",
		"Rope",
		"Sea Charts",
		"Seal of Caelar",
		"Second Stone Fragment",
		"Shakti Figurine",
		"Silver Hilt",
		"Silver Pantaloons",
		"Smuggled Shipment",
		"Solik Berries",
		"Stone Ally",
		"Tears of Bhaal",
		"The Genie's Flask",
		"The Journal of Saemon Havarian",
		"Token of Faith",
		"Tome of Understanding",
		"Viconia's Body",
		"Wardstone",
		"Wardstone for Asylum",
		"Wave Blade",
		"Wooden Stake",
		"Xachrimos's Summoning Stone",
		"rndaro01.itm",
		"rndgem01.itm",
		"rndgem02.itm",
		"rndgem03.itm",
		"rndmag01.itm",
		"rndmag06.itm",
		"rndptn01.itm",
		"rndscr01.itm",
		"rndscr04.itm",
		"rndtre01.itm",
		"rndtre02.itm",
		"rndtre03.itm",
		"rndtre04.itm",
		"rndtre05.itm",
		"rndtre06.itm",
		"rndtre07.itm",
		"rndtre08.itm",
		"rndtre09.itm",
		"rndtri02.itm",
		"rndwand.itm",
		"sodtre09.itm",
	],
	"Books/Broken shields/bracelets": [
		"Book of Rituals",
		"Bounty Notice",
		"Deed to the Windspear Hills",
		"History of Tethyr",
		"History of the Dead Three",
		"History of the Last March of the Giants",
		"History of the Nether Scrolls",
		"Isaea's Slavery Document",
		"Lellyn's Journal",
		"Note",
		"Scrap of Paper",
		"Scroll of Reversal",
		"The Book of Kaza",
		"The Diary of Sarevok",
		"The Journal of Geldorf Tinbasher",
		"Worn Pamphlet",
		"Yago's Book of Curses",
	],
	"Boots": [
		"The Frost's Embrace",
		"The Paws of the Cheetah",
		"Worn Whispers",
	],
	"Bow": [
		"Composite Longbow",
		"Composite Longbow +1",
		"Composite Longbow +2",
		"Composite Longbow +3",
		"Longbow",
		"Longbow +1",
		"Longbow +2",
		"Longbow +3",
		"Shortbow",
		"Shortbow +1",
		"Shortbow +2",
	],
	"Bracers & gauntlets": [
		"Bracers",
		"Bracers of Defense AC 5",
		"Bracers of Defense AC 6",
		"Bracers of Defense AC 7",
		"Bracers of Defense AC 8",
		"Bracers to the Death",
		"Elander's Gloves of Misplacement",
		"Gauntlets of Aln Zekk",
		"Gauntlets of Weapon Skill",
		"Glimmering Bands",
		"Gloves of Missile Snaring",
		"Hands of Takkok",
		"Jansen Techno-Gloves",
		"Legacy of the Masters",
		"Nimblefinger Gloves",
		"The Brawling Hands",
		"The Dale's Protector",
		"Xarrnous's Second Sword Arm",
	],
	"Bullets": [
		"Bullet",
		"Bullet +1",
		"Bullet +2",
		"Bullet of Electricity +1",
		"Bullet of Fire +1",
		"Bullet of Ice +1",
		"Sunstone Bullet +1",
	],
	"Cloaks & Robes": [
		"Algernon's Cloak",
		"Cloak of Atonement",
		"Cloak of Balduran",
		"Cloak of Displacement",
		"Cloak of Dragomir",
		"Cloak of Minor Arcana",
		"Cloak of Mirroring",
		"Cloak of Protection +1",
		"Cloak of the High Forest +1",
		"Cloak of the Shield",
		"Cloak of the Stars",
		"Cowl of the Stars",
		"Drow Piwafwi Cloak",
		"Nymph Cloak",
		"Relair's Mistake",
		"Shadow Thief Cloak",
		"Shandalar's Cloak",
		"The Spirit's Shield +2",
		"Whispers of Silence",
	],
	"Containers/eye/broken armor": [
		"Bag of Holding",
		"Gem Bag",
		"Scroll Case",
	],
	"Crossbow": [
		"Drow Crossbow of Speed +3",
		"Flasher Launcher",
		"Heavy Crossbow",
		"Heavy Crossbow +1",
		"Heavy Crossbow +2",
		"Heavy Crossbow +3",
		"Light Crossbow",
		"Light Crossbow +1",
		"Light Crossbow +2",
	],
	"Dagger": [
		"Boneblade +4",
		"Boomerang Dagger +2",
		"Dagger",
		"Dagger +1",
		"Dagger +2",
		"Heart of the Golem +2",
		"Ixil's Spike",
		"Kylee's Dagger",
		"Poisoned Throwing Dagger",
		"Shadow Thief Dagger",
		"Throwing Dagger",
		"Throwing Dagger +1",
	],
	"Darts": [
		"Asp's Nest +1",
		"Dart",
		"Dart +1",
		"Dart of Acid +1",
		"Dart of Fire +1",
		"Dart of Stunning",
		"Dart of Wounding",
	],
	"Drinks (IWD)": [
		"Empty Wineskin",
		"Wilhelmina's Miracle Turnip Juice",
	],
	"Flail": [
		"Drow Flail +3",
		"Flail",
		"Flail +1",
		"Flail +2",
	],
	"Gem": [
		"Andar Gem",
		"Aquamarine Gem",
		"Black Opal",
		"Bloodstone Gem",
		"Chrysoberyl Gem",
		"Diamond",
		"Dwarven Rune Wardstone",
		"Emerald",
		"Fire Agate Gem",
		"Garnet Gem",
		"Horn Coral Gem",
		"Iol Gem",
		"Jasper Gem",
		"King's Tears",
		"Lynx Eye Gem",
		"Moonbar Gem",
		"Moonstone Gem",
		"Pearl",
		"Rogue Stone",
		"Scepter Gem",
		"Shandon Gem",
		"Skydrop Gem",
		"Sphene Gem",
		"Star Diopside Gem",
		"Sunstone Gem",
		"Tchazar Gem",
		"Turquoise Gem",
		"Wardstone Forgery",
		"Water Opal",
		"Waterstar Gem",
		"Ziose Gem",
	],
	"Halberd": [
		"Halberd",
		"Halberd +1",
		"Halberd +2",
		"Suryris's Blade +2",
	],
	"Hammer": [
		"Aegis-fang +3",
		"The Kneecapper +1",
		"War Hammer",
		"War Hammer +1",
		"War Hammer +3",
	],
	"Headgear": [
		"Battle Tankard",
		"Circlet of Netheril",
		"Helm of the Noble +1",
		"Helmet",
		"Lavender Ioun Stone",
		"Purification Stone",
		"Roranach's Horn",
	],
	"Key": [
		"Beastmaster Key",
		"Branson's Key",
		"Drawbridge Key",
		"Firkraag Prison Key",
		"Guild House Key",
		"Haegan's Key",
		"Holding Pen Key",
		"Intricate Key",
		"Jail Key",
		"Key",
		"Key of Scholars",
		"Key of the Master's Crypt",
		"Korlasz's Key",
		"Monastery Gate Key",
		"Piece of Burial Mask",
		"Portal Key",
		"Ritual Room Key",
		"Sahuagin Treasury Key",
		"Secret Jail Door Key",
		"Sewage Golem Key",
		"Shadow Prison Key",
		"Shadow Thief Prison Key",
		"Slave Pen Key",
		"Temple Key",
		"Tomb Key",
		"Wand of Missiles Key",
	],
	"Large sword": [
		"Abyssal Blade",
		"Bastard Sword",
		"Bastard Sword +1",
		"Bastard Sword +2",
		"Bastard Sword +3",
		"Blackrazor +3",
		"Drow Long Sword +3",
		"Eadro's Blade +1",
		"Hawksight +2",
		"Holy Long Sword of Tyr +3",
		"Long Sword",
		"Long Sword +1",
		"Long Sword +2",
		"Ninja-To",
		"Scimitar",
		"Scimitar +1",
		"The Burning Earth +1",
		"The Ogre's Sword",
		"Twinkle +3",
		"Two-handed Sword",
		"Two-handed Sword +1",
		"Two-handed Sword +2",
		"Two-handed Sword +3",
		"Varscona +2",
	],
	"Mace & Club": [
		"Club",
		"Club +1",
		"Cudgel of Montgomer +1",
		"Mace",
		"Mace +1",
		"Mace +2",
	],
	"Morning star": [
		"Morning Star",
		"Morning Star +1",
		"Morning Star +3",
	],
	"Potion": [
		"Agathor's Near-Universal Solvent",
		"Antidote",
		"Bottle of Wine",
		"De'Tranion's Baalor Ale",
		"Elixir of Health",
		"Empty Breath Potion Flask",
		"Marek's Potion of Antidote",
		"Oil of Fiery Burning",
		"Oil of Speed",
		"Potion of Absorption",
		"Potion of Agility",
		"Potion of Clairvoyance",
		"Potion of Clarity",
		"Potion of Cloud Giant Strength",
		"Potion of Cold Resistance",
		"Potion of Defense",
		"Potion of Explosions",
		"Potion of Extra Healing",
		"Potion of Fire Breath",
		"Potion of Fire Giant Strength",
		"Potion of Fire Resistance",
		"Potion of Fortitude",
		"Potion of Freedom",
		"Potion of Frost Giant Strength",
		"Potion of Genius",
		"Potion of Healing",
		"Potion of Heroism",
		"Potion of Hill Giant Strength",
		"Potion of Infravision",
		"Potion of Insight",
		"Potion of Invisibility",
		"Potion of Invulnerability",
		"Potion of Magic Blocking",
		"Potion of Magic Protection",
		"Potion of Magic Shielding",
		"Potion of Master Thievery",
		"Potion of Mind Focusing",
		"Potion of Mirrored Eyes",
		"Potion of Perception",
		"Potion of Power",
		"Potion of Regeneration",
		"Potion of Stone Form",
		"Potion of Stone Giant Strength",
		"Potion of Storm Giant Strength",
		"Potion of Strength",
		"Potion of Superior Healing",
		"Red Potion",
		"Slime Sickness Curative",
		"Speedily Stolen Slaves' Salve",
		"Violet Potion",
	],
	"Quarterstaff": [
		"Cleric's Staff +3",
		"Neera's Staff +1",
		"Quarterstaff",
		"Quarterstaff +1",
		"Rod of Terror",
		"Staff Spear +2",
	],
	"Ring": [
		"Angel Skin Ring",
		"Batalista's Passport",
		"Bloodstone Ring",
		"Dal Family Ring",
		"Dawn Ring",
		"Discipliner",
		"Dreon's Signet Ring",
		"Druid's Ring",
		"Edventar's Gift",
		"Evermemory",
		"Fire Opal Ring",
		"Flamedance Ring",
		"Gold Ring",
		"Honorary Ring of Sune",
		"Jade Ring",
		"Koveras's Ring of Protection",
		"Nemphre's Onyx Ring",
		"Oaken Ring",
		"Onyx Ring",
		"Ring",
		"Ring of Acuity",
		"Ring of Anti-Venom",
		"Ring of Fire Control",
		"Ring of Fire Resistance",
		"Ring of Free Action",
		"Ring of Human Influence",
		"Ring of Lock Picks",
		"Ring of Protection +1",
		"Ring of Regeneration",
		"Ring of Spell Turning",
		"Ring of Wizardry",
		"Ring of the Princes +1",
		"Ring of the Ram",
		"Ruby Ring",
		"Sandthief's Ring",
		"Sashenstar's Ruby Ring",
		"Silver Ring",
		"The Guard's Ring +2",
		"The Jester's Folly",
		"The Victor",
		"Topsider's Crutch",
		"swordi.itm",
	],
	"Scroll": [
		"Agannazar's Scorcher",
		"Andris's Journal",
		"Animate Dead",
		"Armor",
		"Black Pits Flyer",
		"Blindness",
		"Burning Hands",
		"Chain Lightning",
		"Chaos",
		"Charm Person",
		"Chill Touch",
		"Chromatic Orb",
		"Clairvoyance",
		"Color Spray",
		"Cone of Cold",
		"Confusion",
		"Conjure Earth Elemental",
		"Conjure Fire Elemental",
		"Contact's Note",
		"Contingency",
		"Cure Critical Wounds",
		"Cure Serious Wounds",
		"Cursed Scroll of Petrification",
		"Cursed Scroll of Weakness",
		"Dark Moon Note",
		"Death Fog",
		"Death Spell",
		"Delayed Blast Fireball",
		"Demin's Note",
		"Detect Evil",
		"Dezkiel's Scroll",
		"Dire Charm",
		"Disintegrate",
		"Dispel Magic",
		"Domination",
		"Emotion: Hopelessness",
		"Feeblemind",
		"Find Familiar",
		"Fireball",
		"Fireshield (Blue)",
		"Fireshield (Red)",
		"Flame Arrow",
		"Flesh to Stone",
		"Friends",
		"Geas Removal Scroll",
		"Ghost Armor",
		"Ghoul Touch",
		"Glitterdust",
		"Grease",
		"Greater Malison",
		"Haste",
		"Hold Monster",
		"Hold Person",
		"Horror",
		"Identify",
		"Improved Haste",
		"Infravision",
		"Invitation",
		"Knock",
		"Know Alignment",
		"Larloch's Minor Drain",
		"Letter",
		"Letter to Kryll",
		"Lightning Bolt",
		"Luck",
		"Magic Missile",
		"Melf's Acid Arrow",
		"Minor Globe of Invulnerability",
		"Minor Sequencer",
		"Minor Spell Turning",
		"Mirror Image",
		"Mislead",
		"Monster Summoning I",
		"Monster Summoning III",
		"Non-Detection",
		"Note",
		"Oracle",
		"Otiluke's Resilient Sphere",
		"Protection From Evil",
		"Protection From Fire",
		"Protection From Magic",
		"Protection From Normal Missiles",
		"Protection From Petrification",
		"Protection From Poison",
		"Protection From Undead",
		"Remove Curse",
		"Remove Magic",
		"Resist Fear",
		"Scroll",
		"Seditious Letter",
		"Shadow Door",
		"Shield",
		"Shocking Grasp",
		"Skull Trap",
		"Sleep",
		"Slow",
		"Sorrem's Note",
		"Spell Sequencer",
		"Spell Thrust",
		"Spell Trigger",
		"Spell Turning",
		"Spellstrike",
		"Spider Spawn",
		"Spirit Armor",
		"Stinking Cloud",
		"Stone to Flesh",
		"Stone to Flesh Scroll",
		"Stoneskin",
		"Strength",
		"Summon Efreeti",
		"Summon Nishruu",
		"Tizzak's Journal",
		"True Sight",
		"Tsolak's Scroll",
		"Vampiric Touch",
		"Vocalize",
		"Web",
		"Wraithform",
	],
	"Shield": [
		"Buckler +1",
		"Large Shield",
		"Large Shield +2",
		"Medium Shield",
		"Medium Shield +1",
		"Reed of Echoes",
		"The Suncatcher +2",
	],
	"Sling": [
		"Sling ",
		"Sling +1",
		"Sling +2",
	],
	"Small sword": [
		"Short Sword",
		"Short Sword +1",
		"Short Sword +2",
		"Short Sword +3",
		"Sword of Arvoreen +2",
		"The Shadow's Blade +3",
		"The Whistling Sword +2",
		"Wakizashi",
	],
	"Spear": [
		"Backbiter +3",
		"Impaler +3",
		"Spear",
		"Spear +2",
		"Spear +3",
	],
	"Tattoos": [
		"Bandit Scalp",
	],
	"Unknown": [
		"Herdrin's Body",
		"Iron Rod",
		"Kendra's Body",
		"Lexa's Body",
	],
	"Wand": [
		"Rod of Resurrection",
		"Rod of Shadowstep",
		"Wand of Cloudkill",
		"Wand of Cursing",
		"Wand of Fear",
		"Wand of Fire",
		"Wand of Frost",
		"Wand of Lightning",
		"Wand of Magic Missiles",
		"Wand of Monster Summoning",
		"Wand of Paralyzation",
		"Wand of Polymorphing",
		"Wand of Sleep",
		"Wand of Spell Striking",
		"Wand of the Heavens",
	],
}
