gamestr = "Baldur's Gate EET 2.6.5.0 + SCS"
headers = ["Area", "NPC", "XP", "Gold Carried", "Pickpocket Skill", "Item Price (base)", "Item Type", "Item"]

areas = [
	"act04 (Spawned)",
	"act05 (Spawned)",
	"act06 (Spawned)",
	"actboun (Spawned)",
	"actnesto (Spawned)",
	"aerie (Spawned)",
	"aldcut01 (Spawned)",
	"aldcut02 (Spawned)",
	"ambush2 (Spawned)",
	"ammerc (Spawned)",
	"ammgrd (Spawned)",
	"ammlegs (Spawned)",
	"amntrp02 (Spawned)",
	"amntrp03 (Spawned)",
	"anomen (Spawned)",
	"ar0020 (Spawned) - City Gates",
	"ar0020 - City Gates",
	"ar0021 - Crooked Crane 1st Floor",
	"ar0022 (Spawned) - Crooked Crane 2nd Floor",
	"ar0028 - Candlekeep Dream (After PC Soultheft)",
	"ar0041 (Spawned) - Random Encounter City",
	"ar0042 (Spawned) - Random Encounter Outdoor",
	"ar0043 (Spawned) - Random Encounter Outdoor (With rocks)",
	"ar0044 (Spawned) - Random Encounter Outdoor (sand)",
	"ar0045 (Spawned) - Random Encounter City",
	"ar0046 (Spawned) - Random Encounter City (bridge)",
	"ar0071 - \"Spellhold (Imoen Soultheft Cutscene -- \"\"Silence do, you have no purpose...\"\")\"",
	"ar0072 - Ust Natha Temple (Irenicus/Bodhi, Ardula/Phaere Cutscene)",
	"ar0082 - Lich Grave in Bridge District Inn",
	"ar0202 - The Unseeing Eye Cult Hideout",
	"ar0206 - Ghoul village (Temple District)",
	"ar0300 (Spawned) - The Docks",
	"ar0300 - The Docks",
	"ar0301 - Mae'Var's Hide Out",
	"ar0302 - Mae'Var's Inn 1st Floor -- Entrance",
	"ar0303 - Mae'Var's Inn 2nd Floor -- Training Area",
	"ar0304 (Spawned) - Mae'Var's Inn 3rd Floor -- Edwin",
	"ar0305 - Shadow Thieves Guild Entrance",
	"ar0306 - Renal Bloodscalp's Hideout",
	"ar0307 - Aran Linvail's Hideout",
	"ar0308 (Spawned) - Harper's 1st Floor",
	"ar0308 - Harper's 1st Floor",
	"ar0311 (Spawned) - Living Room (Entry points outside and up) -- Gaelan?",
	"ar0312 - Sleeping Room (Entry point down) -- Arledrian",
	"ar0313 (Spawned) - Sea Bounty Tavern 1st Floor",
	"ar0313 - Sea Bounty Tavern 1st Floor",
	"ar0314 (Spawned) - Sea Bounty Tavern 2nd Floor",
	"ar0314 - Sea Bounty Tavern 2nd Floor",
	"ar0317 - Sleeping Room (Favour for Edwin -- Mae'Var Plot)",
	"ar0319 - Temple of Oghma",
	"ar0322 (Spawned) - Thief Stronghold (1st Floor)",
	"ar0322 - Thief Stronghold (1st Floor)",
	"ar0329 - Aran's Hideout (sided with Bodhi)",
	"ar0332 - Barracks in the Docks",
	"ar0333 - Barracks in the Docks",
	"ar0400 (Spawned) - Slums",
	"ar0400 - Slums",
	"ar0401 - Jansen Cellar",
	"ar0402 (Spawned) - Jansen 1st Floor",
	"ar0402 - Jansen 1st Floor",
	"ar0403 (Spawned) - Jansen 2nd Floor",
	"ar0404 - Sewers beneath Coronet -- Lilarcor",
	"ar0405 - Slaver's Ship Building",
	"ar0406 (Spawned) - Copper Coronet",
	"ar0406 - Copper Coronet",
	"ar0407 - Prebek's House",
	"ar0408 - Temple of Ilmater",
	"ar0410 - Sphere: Navigator's room -- Lavok's Hideout",
	"ar0411 (Spawned) - Sphere: Entrance floor",
	"ar0411 - Sphere: Entrance floor",
	"ar0412 - Sphere: Ice and Fire Room",
	"ar0414 - Sphere: Demon Plane",
	"ar0415 (Spawned) - Living Room 1st Floor",
	"ar0417 (Spawned) - Living Room",
	"ar0418 - Myconids",
	"ar0500 (Spawned) - Bridge District",
	"ar0500 - Bridge District",
	"ar0501 (Spawned) - Tanner's Hideout 1st Floor",
	"ar0504 - Saerk's House 1st Floor",
	"ar0505 (Spawned) - Saerk's House 2nd Floor",
	"ar0505 - Saerk's House 2nd Floor",
	"ar0506 - Noble House 1st Floor",
	"ar0507 - Kidnappers' Hideout 1st Floor",
	"ar0509 - Five Flagons Inn 1st Floor",
	"ar0510 - Five Flagons Inn Theater",
	"ar0511 (Spawned) - Five Flagons Inn 2nd Floor",
	"ar0511 - Five Flagons Inn 2nd Floor",
	"ar0512 - Temple of Helm",
	"ar0513 (Spawned) - Calbor's Inn at Bridge District 1st Floor",
	"ar0513 - Calbor's Inn at Bridge District 1st Floor",
	"ar0514 - Inn at Bridge District 2nd Floor",
	"ar0515 - Inn at Bridge District 3rd Floor",
	"ar0516 - Planar Prison",
	"ar0522 (Spawned) - Five Flagons Inn (Stronghold)",
	"ar0522 - Five Flagons Inn (Stronghold)",
	"ar0523 (Spawned) - Five Flagons Theater (Stronghold)",
	"ar0529 (Spawned) - Neb's Hideout",
	"ar0602 - Irenicus's Dungeon 1st Floor",
	"ar0603 - Irenicus's Dungeon 2nd Floor",
	"ar0604 - Circus Tent 1st Floor",
	"ar0606 - Circus Tent 3rd Floor",
	"ar0607 (Spawned) - Circus Tent restored",
	"ar0700 (Spawned) - Waukeen's Promenade",
	"ar0700 - Waukeen's Promenade",
	"ar0701 (Spawned) - The Sewers",
	"ar0701 - The Sewers",
	"ar0702 (Spawned) - Adventurer's Mart",
	"ar0702 - Adventurer's Mart",
	"ar0704 (Spawned) - Mithrest Inn",
	"ar0704 - Mithrest Inn",
	"ar0705 - Mekrath's Hideout in the Sewers (Haer'Dalis Plot)",
	"ar0706 - Armourer/Fletcher",
	"ar0707 - Enge's Shop",
	"ar0709 - Den of the Seven Vales 1st Floor",
	"ar0712 - Den of the Seven Vales 2nd Floor",
	"ar0713 - Store or Inn at Promenade",
	"ar0800 (Spawned) - Graveyard",
	"ar0800 - Graveyard",
	"ar0801 (Spawned) - Bodhi's Hideout (sided with Aran)",
	"ar0802 (Spawned) - Netherscroll, Korgan's Book, Edwin",
	"ar0804 - Pai'Na's Hideout",
	"ar0806 - Crypt",
	"ar0808 (Spawned) - Bodhi's Hideout (Abduction Plot, getting Imoen's soul)",
	"ar0808 - Bodhi's Hideout (Abduction Plot, getting Imoen's soul)",
	"ar0809 (Spawned) - Bodhi's Lair (Abduction Plot, getting Imoen's soul)",
	"ar0900 (Spawned) - Temple District",
	"ar0900 - Temple District",
	"ar0901 (Spawned) - Temple of Helm",
	"ar0901 - Temple of Helm",
	"ar0902 (Spawned) - Temple of Lathander",
	"ar0902 - Temple of Lathander",
	"ar0903 - Order of the Radiant Heart",
	"ar0904 (Spawned) - Temple of Talos",
	"ar0904 - Temple of Talos",
	"ar0905 - Pimlico's Estate",
	"ar1000 (Spawned) - Government District",
	"ar1000 - Government District",
	"ar1001 (Spawned) - Delryn's Estate",
	"ar1001 - Delryn's Estate",
	"ar1002 - Councel Building",
	"ar1003 - Firecam's Estate",
	"ar1005 - Prison",
	"ar1006 (Spawned) - Jysstev's Estate (Oisig Plot)",
	"ar1006 - Jysstev's Estate (Oisig Plot)",
	"ar1007 (Spawned) - Noble House",
	"ar1010 - Temple of Waukeen",
	"ar1100 (Spawned) - Umar Hills",
	"ar1100 - Umar Hills",
	"ar1103 - Jermien's Cabin",
	"ar1104 (Spawned) - Mayor Lloyd's Cabin",
	"ar1105 (Spawned) - Imnesvale Inn",
	"ar1105 - Imnesvale Inn",
	"ar1200 (Spawned) - Windspear Hills",
	"ar1200 - Windspear Hills",
	"ar1201 - Firkraag's Entrance",
	"ar1202 (Spawned) - Firkaag's Maze",
	"ar1202 - Firkaag's Maze",
	"ar1203 - Firkraag's Hideout",
	"ar1204 (Spawned) - Garren Windspear's Cabin",
	"ar1300 (Spawned) - De'Arnise Keep Destroyed",
	"ar1300 - De'Arnise Keep Destroyed",
	"ar1301 - De'Arnise Cellar",
	"ar1302 (Spawned) - De'Arnise Keep 1st Floor",
	"ar1303 - De'Arnise Keep 2nd Floor (Destroyed)",
	"ar1304 (Spawned) - De'Arnise Keep (Restored, Stronghold)",
	"ar1304 - De'Arnise Keep (Restored, Stronghold)",
	"ar1306 (Spawned) - De'Arnise Keep (Stronghold)",
	"ar1306 - De'Arnise Keep (Stronghold)",
	"ar1400 (Spawned) - Shadow Temple Land (restored, Ranger)",
	"ar1400 - Shadow Temple Land (restored, Ranger)",
	"ar1401 (Spawned) - Shadow Temple",
	"ar1401 - Shadow Temple",
	"ar1404 - Shadow Temple Land shadowed",
	"ar1600 (Spawned) - Brynnlaw",
	"ar1600 - Brynnlaw",
	"ar1602 - Brynnlaw's Inn",
	"ar1603 - Brynnlaw's Shop",
	"ar1605 - CW's House",
	"ar1606 (Spawned) - House of Desharik's Lover",
	"ar1607 - Githyanki Assault",
	"ar1610 - Brothel Prison",
	"ar1611 - Brothel",
	"ar1612 - Brothel Kitchen",
	"ar1800 - North Forest",
	"ar1900 (Spawned) - Druid Grove Area",
	"ar1900 - Druid Grove Area",
	"ar1901 (Spawned) - Druid Grove",
	"ar1901 - Druid Grove",
	"ar1902 - Storehouse (Ihtafeer's Storehouse)",
	"ar1905 (Spawned) - Store Tower",
	"ar2000 (Spawned) - Trademeet",
	"ar2000 - Trademeet",
	"ar2002 - Fentan's House",
	"ar2007 - High Merchant's Estate",
	"ar2008 - Temple of Waukeen",
	"ar2010 - Trademeet's Inn",
	"ar2011 (Spawned) - Alibakkar's Estate",
	"ar2011 - Alibakkar's Estate",
	"ar2012 (Spawned) - Lurraxol's Estate",
	"ar2012 - Lurraxol's Estate",
	"ar2015 - Merchant Tent",
	"ar2017 - Courtesan Tent",
	"ar2100 (Spawned) - Underdark",
	"ar2100 - Underdark",
	"ar2200 (Spawned) - Ust Natha",
	"ar2200 - Ust Natha",
	"ar2201 (Spawned) - Temple in Ust Natha",
	"ar2201 - Temple in Ust Natha",
	"ar2202 - Inn in Ust Natha 1st Floor",
	"ar2203 - Inn in Ust Natha; 2nd Floor",
	"ar2205 (Spawned) - House in Ust Natha",
	"ar2206 - Qilue's House in Ust Natha",
	"ar2207 - Deirex's Tower in Ust Natha",
	"ar2208 - Jarlaxle's House wherever",
	"ar2209 - Jae'llat's House",
	"ar2300 (Spawned) - Sahuagin City",
	"ar2300 - Sahuagin City",
	"ar2401 - Cave Between Underdark and Exit from Underdark",
	"ar2402 (Spawned) - Kuo Toa in Underdark",
	"ar2402 - Kuo Toa in Underdark",
	"ar2600 (Spawned) - Thetyr Wood",
	"ar2600 - Thetyr Wood",
	"ar2601 (Spawned) - Meet Drizzt Do'Urden",
	"ar2800 (Spawned) - Suldanessellar",
	"ar2800 - Suldanessellar",
	"ar2801 - House of High Priestess of Suldanessellar",
	"ar2806 (Spawned) - Tree of Life",
	"ar2806 - Tree of Life",
	"ar2903 - Greed (Abyss)",
	"ar2904 - Selfish (Abyss)",
	"ar3000 - Watcher's Keep",
	"ar3001 - Watcher's Keep -- Altar level",
	"ar3005 - Watcher's Keep -- tieflings",
	"ar3006 - Watcher's Keep -- Succubus",
	"ar3012 - Watcher's Keep -- Tahazzar",
	"ar3013 (Spawned) - Watcher's Keep -- Ka'rashur",
	"ar3013 - Watcher's Keep -- Ka'rashur",
	"ar3015 - Watcher's Keep -- Aesgareth",
	"ar3016 - Watcher's Keep -- Chromatic Demon; Elementalist Level",
	"ar4500 (Spawned) - Pocket Plane",
	"ar5000 - Saradush",
	"ar5002 - Gromnir's Hideout",
	"ar5003 - Saradush Tavern (Tankard Tree)",
	"ar5004 - Temple of Waukeen",
	"ar5007 (Spawned) - Basement Entrance to Gromnir's Hideout",
	"ar5007 - Basement Entrance to Gromnir's Hideout",
	"ar5008 (Spawned) - Kiser's Home",
	"ar5009 (Spawned) - House (no exit?)",
	"ar5011 - Arcana Archives",
	"ar5013 - Sewers beneath Saradush",
	"ar5014 (Spawned) - Kiser's Home -- Cellar",
	"ar5014 - Kiser's Home -- Cellar",
	"ar5015 (Spawned) - Saradush Militia Entrance",
	"ar5016 - Saradush Castle Jail (Kiser Plot)",
	"ar5200 - Fire Giant Entrance Area",
	"ar5202 - Nyalee's Hideout; Gorion Wraith",
	"ar5203 (Spawned) - Yaga-Shura's Camp",
	"ar5500 (Spawned) - Amkethran",
	"ar5500 - Amkethran",
	"ar5501 (Spawned) - Amkethran Inn",
	"ar5501 - Amkethran Inn",
	"ar5502 - Kerrick the Smith's House",
	"ar5504 (Spawned) - Smuggler Cave",
	"ar5504 - Smuggler Cave",
	"ar5506 - Commoner's Home",
	"ar5508 - Faheed's Home",
	"ar6000 (Spawned) - Abazigal's Entrance",
	"ar6000 - Abazigal's Entrance",
	"ar6001 - Abazigal's Lair Entrance Hall",
	"ar6002 - Abazigal's Lair -- Cells",
	"ar6003 - Abazigal's Lair -- Iycanth the Mad, Bondari",
	"ar6100 (Spawned) - Area outside Sendai's Hideout",
	"ar6100 - Area outside Sendai's Hideout",
	"ar6102 - Sendai's Lair -- Slavemaster",
	"ar6106 - Sendai's Lair -- Captain Egeissag",
	"ar6108 (Spawned) - Sendai's Lair -- Sendai",
	"ar6108 - Sendai's Lair -- Sendai",
	"ar6300 - Oasis in Tethyr",
	"ar6400 - River Area",
	"arnspw1 (Spawned)",
	"baldur (Spawned)",
	"baldur25 (Spawned)",
	"bancut01 (Spawned)",
	"bancut02 (Spawned)",
	"bd0010 (Spawned) - Ducal Palace City Exterior",
	"bd0010 - Ducal Palace City Exterior",
	"bd0020 (Spawned) - Sorcerous/Elf Song City Exterior",
	"bd0020 - Sorcerous/Elf Song City Exterior",
	"bd0021",
	"bd0030 - Flaming Fist City Exterior",
	"bd0035",
	"bd0040 (Spawned) - Three Kegs City Exterior",
	"bd0040 - Three Kegs City Exterior",
	"bd0050 (Spawned) - Iron Throne City Exterior",
	"bd0050 - Iron Throne City Exterior",
	"bd0064 - Random Area - Forest Paths",
	"bd0100 (Spawned) - Ducal Palace, Second Floor",
	"bd0100 - Ducal Palace, Second Floor",
	"bd0101 (Spawned) - Ducal Palace, Leaving BG",
	"bd0101 - Ducal Palace, Leaving BG",
	"bd0102 (Spawned) - Ducal Palace, First Floor",
	"bd0102 - Ducal Palace, First Floor",
	"bd0103 (Spawned) - Ducal Palace, Third Floor",
	"bd0103 - Ducal Palace, Third Floor",
	"bd0104 (Spawned) - Flaming Fist HQ",
	"bd0104 - Flaming Fist HQ",
	"bd0106 - Three Old Kegs, First Floor",
	"bd0107 - Three Old Kegs, Second Floor",
	"bd0108 (Spawned) - Three Old Kegs, Third Floor",
	"bd0108 - Three Old Kegs, Third Floor",
	"bd0109 - Elfsong Tavern, First Floor",
	"bd0110 (Spawned) - Elfsong Tavern, Second Floor",
	"bd0110 - Elfsong Tavern, Second Floor",
	"bd0111 (Spawned) - Iron Throne Floor, First Floor",
	"bd0111 - Iron Throne Floor, First Floor",
	"bd0112 - Baldur's Gate East",
	"bd0116 (Spawned) - Ducal Palace, Basement",
	"bd0120 (Spawned) - Tomb Safehouse, First Floor",
	"bd0120 - Tomb Safehouse, First Floor",
	"bd0122 (Spawned) - Sorcerous Sundries, Second Floor",
	"bd0130 - Tomb Safehouse, Second Floor",
	"bd1000 (Spawned) - Coast Way Crossing",
	"bd1000 - Coast Way Crossing",
	"bd1100 - The Dig",
	"bd1200 - Lich Outpost",
	"bd2000 (Spawned) - Boareskyr Bridge & Bridgefort",
	"bd2000 - Boareskyr Bridge & Bridgefort",
	"bd2100 (Spawned) - Bridgefort Interior",
	"bd2100 - Bridgefort Interior",
	"bd3000 (Spawned) - Allied Siege Camp",
	"bd3000 - Allied Siege Camp",
	"bd4000 (Spawned) - Dragonspear Castle, Exterior",
	"bd4000 - Dragonspear Castle, Exterior",
	"bd4100 (Spawned) - Dragonspear Castle Keep, First Floor",
	"bd4100 - Dragonspear Castle Keep, First Floor",
	"bd4300 (Spawned) - Dragonspear Castle Basement",
	"bd4300 - Dragonspear Castle Basement",
	"bd4400 - Avernus",
	"bd4700 - Avernus Roof",
	"bd5000 (Spawned) - Underground River Entrance",
	"bd5000 - Underground River Entrance",
	"bd5100 (Spawned) - Underground River",
	"bd5100 - Underground River",
	"bd5200 - The Warrens",
	"bd5300 - Kanaglym",
	"bd6000 (Spawned) - Abandoned Sewers & Caverns",
	"bd6100 (Spawned) - The Ambush",
	"bd7000 (Spawned) - Coast Way Forest",
	"bd7000 - Coast Way Forest",
	"bd7100 (Spawned) - Troll Forest",
	"bd7100 - Troll Forest",
	"bd7200 - Forest of Wyrms",
	"bd7220 (Spawned) - Bugbear Stronghold",
	"bd7230 - Temple of Cyric",
	"bd7300 - Dead Man's Pass",
	"bd7400 - Bloodbark Grove",
	"bdboarb2 (Spawned)",
	"bdbranch (Spawned)",
	"bdbteam1 (Spawned)",
	"bdbteam2 (Spawned)",
	"bdbteam3 (Spawned)",
	"bdbteam4 (Spawned)",
	"bdbteam5 (Spawned)",
	"bdbteam6 (Spawned)",
	"bdc123a (Spawned)",
	"bdc205aa (Spawned)",
	"bdc205ab (Spawned)",
	"bdc205ac (Spawned)",
	"bdc205ba (Spawned)",
	"bdc205bb (Spawned)",
	"bdc205bc (Spawned)",
	"bdc205ca (Spawned)",
	"bdc205cb (Spawned)",
	"bdc205da (Spawned)",
	"bdc205db (Spawned)",
	"bdc205r (Spawned)",
	"bdcut09 (Spawned)",
	"bdcut09a (Spawned)",
	"bdcut09b (Spawned)",
	"bdcut11 (Spawned)",
	"bdcut11a (Spawned)",
	"bdcut15 (Spawned)",
	"bdcut16 (Spawned)",
	"bdcut20a (Spawned)",
	"bdcut21 (Spawned)",
	"bdcut26 (Spawned)",
	"bdcut27 (Spawned)",
	"bdcut28 (Spawned)",
	"bdcut30a (Spawned)",
	"bdcut322 (Spawned)",
	"bdcut36 (Spawned)",
	"bdcut40a (Spawned)",
	"bdcut40b (Spawned)",
	"bdcut40c (Spawned)",
	"bdcut40d (Spawned)",
	"bdcut41 (Spawned)",
	"bdcut42 (Spawned)",
	"bdcut43 (Spawned)",
	"bdcut45 (Spawned)",
	"bdcut45a (Spawned)",
	"bdcut58 (Spawned)",
	"bdcut59b (Spawned)",
	"bdcut60a (Spawned)",
	"bdcut60b (Spawned)",
	"bdcut60x (Spawned)",
	"bdcut61t (Spawned)",
	"bdcut62 (Spawned)",
	"bdcut64 (Spawned)",
	"bdddd2a (Spawned)",
	"bdddd2b (Spawned)",
	"bdddd3a (Spawned)",
	"bddebug (Spawned)",
	"bddmspwn (Spawned)",
	"bddoor30 (Spawned)",
	"bddsgat1 (Spawned)",
	"bdexduel (Spawned)",
	"bdintro (Spawned)",
	"bdnorest (Spawned)",
	"bdscry01 (Spawned)",
	"bdscry03 (Spawned)",
	"bdscry05 (Spawned)",
	"bdsdd251 (Spawned)",
	"bdsddski (Spawned)",
	"bdshcut0 (Spawned)",
	"bdwaterf (Spawned)",
	"bg0004 - Behren's home, ground floor",
	"bg0006 - Rinnie's home, ground floor",
	"bg0010 - Jardak's home, ground floor (Drelik the butler)",
	"bg0011 - Jardak's home, second floor",
	"bg0102 - Silvershield Estate, second floor",
	"bg0103 (Spawned) - Splurging Sturgeon, ground floor (Lusselyn)",
	"bg0105 - Blade and Stars, ground floor (G'axir the Seer, Elkart)",
	"bg0106 (Spawned) - Blade and Stars, second floor (Maple Willow Aspen)",
	"bg0108 (Spawned) - Duchal Palace, ground floor",
	"bg0112 (Spawned) - Undercellars (Slythe, Krystin)",
	"bg0112 - Undercellars (Slythe, Krystin)",
	"bg0114 (Spawned) - Blushing Mermaid, ground floor (Larze)",
	"bg0114 - Blushing Mermaid, ground floor (Larze)",
	"bg0115 (Spawned) - Blushing Mermaid, second floor",
	"bg0116 - Helm & Cloak, ground floor (Gorpel Hind)",
	"bg0119 - Three Old Kegs tavern, ground floor",
	"bg0120 - Three Old Kegs tavern, second floor (Skull of Keraph)",
	"bg0121 - Three Old Kegs tavern, third floor (Areana)",
	"bg0123 - Undercity (Temple of Bhaal, old city ruins)",
	"bg0125 - Temple of Bhaal (game finale)",
	"bg0126 - Ragefast's home",
	"bg0128 (Spawned) - Merchant League, second floor (Aldeth, Brandilar, Zorl)",
	"bg0128 - Merchant League, second floor (Aldeth, Brandilar, Zorl)",
	"bg0130 - Hall of Wonders (Alora)",
	"bg0131 - Temple of Gond (Forthel August)",
	"bg0132 - Lady's House (Agnasia, Chanthalas Ulbright)",
	"bg0134 - Low Lantern, first underwater level (Desreta, Vay-ya)",
	"bg0135 - Low Lantern, second underwater level (Yago)",
	"bg0137 (Spawned) - Ramazith's Tower, ground floor",
	"bg0143 - Oberan's Estate, ground floor",
	"bg0145 - Oberan's Estate, third floor (Helshara, Ithmeera, Delorna)",
	"bg0148 (Spawned) - Thieves Guild, front house (fourth from west)",
	"bg0150 (Spawned) - Thieves Guild, front house (first from west)",
	"bg0151 (Spawned) - Thieves Guild, front house (second from west)",
	"bg0152 (Spawned) - Thieves Guild, front house (third from west)",
	"bg0153 (Spawned) - Thieves Guild, main area (Alatos, Narlen Darkwalk)",
	"bg0153 - Thieves Guild, main area (Alatos, Narlen Darkwalk)",
	"bg0162 - Louise and Laerta's home",
	"bg0167 - Phierkas's home, ground floor",
	"bg0200 - N Baldur's Gate (Ramazith's Tower, Duchal Palace)",
	"bg0224 - BG Sewers, western area (Schlumpsha the Sewer King)",
	"bg0225 - BG Sewers, central area (Ratchild)",
	"bg0226 - BG Sewers, eastern area (ogre mage for Scar)",
	"bg0300 (Spawned) - NE Baldur's Gate (Blushing Mermaid, Splurging Sturgeon, Counting House)",
	"bg0300 - NE Baldur's Gate (Blushing Mermaid, Splurging Sturgeon, Counting House)",
	"bg0304 - Generic store",
	"bg0307 (Spawned) - Counting House, ground floor (Jacil or Ulf)",
	"bg0307 - Counting House, ground floor (Jacil or Ulf)",
	"bg0308 (Spawned) - Counting House, second floor (Captain Kieres)",
	"bg0500 (Spawned) - Durlag's Tower, exterior",
	"bg0501 - Durlag's Tower, first subterranean level",
	"bg0504 - Durlag's Tower, third floor (Rigglio)",
	"bg0505 - Durlag's Tower, fourth floor (Kirinhale)",
	"bg0514 - Durlag's Tower, fifth subterranean level",
	"bg0516 - Durlag's Tower, demon knight chamber (Dalton)",
	"bg0601 - Seven Suns, ground floor",
	"bg0602 - Seven Suns, second floor",
	"bg0608 (Spawned) - Flaming Fist HQ, second floor (Duke Eltan)",
	"bg0612 (Spawned) - Iron Throne, second floor (Dra'tan)",
	"bg0612 - Iron Throne, second floor (Dra'tan)",
	"bg0613 - Iron Throne, third floor (Nortuary, Emissary Tar)",
	"bg0615 (Spawned) - Iron Throne, fifth (top) floor (chapter five finale)",
	"bg0615 - Iron Throne, fifth (top) floor (chapter five finale)",
	"bg0616 (Spawned) - Iron Throne, ground floor (Triadore)",
	"bg0617 (Spawned) - Tremain Belde'ar's home, ground floor",
	"bg0700 (Spawned) - Central Baldur's Gate (marketplace, Oberan's home)",
	"bg0703 - Sorcerous Sundries, ground floor (Halbazzer Drin)",
	"bg0704 - Sorcerous Sundries, second floor",
	"bg0705 (Spawned) - Elfsong Tavern, ground floor (Brevlik)",
	"bg0705 - Elfsong Tavern, ground floor (Brevlik)",
	"bg0706 - Elfsong Tavern, second floor (Alyth, Cyrdemac)",
	"bg0715 - Nadine's home, ground floor",
	"bg0800 (Spawned) - E Baldur's Gate (Sorcerous Sundries, Elfsong Tavern)",
	"bg0800 - E Baldur's Gate (Sorcerous Sundries, Elfsong Tavern)",
	"bg0803 - Maltz's Weapon Shop, ground floor",
	"bg0805 - Arkion's home, ground floor",
	"bg0809 (Spawned) - Silence's store",
	"bg0810 - Luck Aello's store",
	"bg0813 - Nemphre's home, ground floor",
	"bg0900 (Spawned) - Wyrm's Crossing (bridge to BG, Tenya, Quayle)",
	"bg0900 - Wyrm's Crossing (bridge to BG, Tenya, Quayle)",
	"bg1000 (Spawned) - Ulgoth's Beard (Shandalar, Ike, Mendas)",
	"bg1000 - Ulgoth's Beard (Shandalar, Ike, Mendas)",
	"bg1001 - Ulgoth Beard's Inn (Hurgan Stoneblade)",
	"bg1002 (Spawned) - Aec'Letec cult building, basement (Aec'Letec)",
	"bg1003 (Spawned) - Aec'Letec cult building, ground floor",
	"bg1005 - Therella's home",
	"bg1009 - Ice island, dungeon",
	"bg1010 - Ice island, unused exit area",
	"bg1100 (Spawned) - SW Baldur's Gate (Flaming Fist HQ, Merchant League, Seven Suns)",
	"bg1101 - Generic home, ground floor (thieves Wiven, Dirk, Meakin and Sath)",
	"bg1111 - Sunin's home",
	"bg1112 - Generic weapons store",
	"bg1115 - Generic potions store",
	"bg1116 - Generic weapons store",
	"bg1117 - Generic potions store",
	"bg1200 (Spawned) - S Baldur's Gate (docks, Iron Throne, Low Lantern, Umberlee temple)",
	"bg1200 - S Baldur's Gate (docks, Iron Throne, Low Lantern, Umberlee temple)",
	"bg1208 - Warehouse (Noralee)",
	"bg1209 - Generic home, ground floor (Larriaz the Sirine)",
	"bg1213 - Cordyr's home, ground floor",
	"bg1300 (Spawned) - SE Baldur's Gate (Blade and Stars)",
	"bg1302 - Well-Adjusted Al's General Store",
	"bg1303 - Warehouse (Nadarin)",
	"bg1316 - Generic home, ground floor (thieves Taxek and Michael)",
	"bg1320 - Generic store",
	"bg1400 - Fishing village (Ajantis, farmer Brun, Gerde, lots of ankhegs)",
	"bg1500 (Spawned) - Balduran's Isle, north (AKA Werewolf Isle)",
	"bg1500 - Balduran's Isle, north (AKA Werewolf Isle)",
	"bg1504 - Balduran's ship, fourth floor (Karoug)",
	"bg1600 - Cloakwood, third main area (shadow druids, Eldoth, Faldorn)",
	"bg1603 - Baby wyvern cave (Peter of the North)",
	"bg1800 - Cloakwood mines, exterior",
	"bg1802 - Cloakwood mines, third subterranean level (Natasha, ogre mage)",
	"bg1803 - Cloakwood mines, fourth subterranean level (Davaeorn, Stephan)",
	"bg1900 (Spawned) - Bandit Camp",
	"bg1900 - Bandit Camp",
	"bg1901 - Bandit Camp, main tent (Raemon, Venkt, Hakt, Britik)",
	"bg1902 - Bandit Camp, tent (Ardenor Crush)",
	"bg1903 - Bandit Camp, cave (Garclax)",
	"bg1904 - Bandit Camp, tent (Tersus)",
	"bg1905 - Bandit Camp, tent (Knott)",
	"bg2000 (Spawned) - Balduran's Isle, south (AKA Werewolf Isle, Delainy/Durlyle)",
	"bg2000 - Balduran's Isle, south (AKA Werewolf Isle, Delainy/Durlyle)",
	"bg2101 - Spider nest (Centeol)",
	"bg2200 - Cloakwood, first main area (Aldeth Sashenstar, Seniyad, Coran)",
	"bg2300 - Friendly Arm Inn, exterior",
	"bg2302 - Friendly Arm Inn, second floor (Unshey)",
	"bg2303 - Friendly Arm Inn, third floor (Landrin, Golden Pantaloons)",
	"bg2304 - Friendly Arm Inn, Temple of Wisdom (Gellana Mirrorshade)",
	"bg2400 (Spawned) - Peldvale (Viconia, Raiken)",
	"bg2400 - Peldvale (Viconia, Raiken)",
	"bg2600 - Candlekeep (prologue), exterior",
	"bg2602 - Candlekeep (prologue), Priest's Quarters (Shank)",
	"bg2605 - Candlekeep (prologue), infirmary",
	"bg2607 - Candlekeep (prologue), bunkhouse (Carbos)",
	"bg2609 - Candlekeep Citadel, second floor (Koveras)",
	"bg2610 - Candlekeep Citadel, third floor (Rieltar, Brunos Costak, Tuth and Kestor)",
	"bg2614 - Candlekeep Citadel, sixth floor (Ulraunt, Tethtoril)",
	"bg2615 - Candlekeep Catacombs, first level",
	"bg2616 - Candlekeep (prologue), Inn ground floor",
	"bg2618 - Candlekeep (prologue), barracks",
	"bg2619 - Candlekeep Catacombs, second level",
	"bg2626 (Spawned) - Candlekeep (chapter 6), exterior",
	"bg2626 - Candlekeep (chapter 6), exterior",
	"bg2629 - Candlekeep (chapter 6), Inn ground floor",
	"bg2631 - Candlekeep (chapter 6), barracks",
	"bg2639 - Unused",
	"bg2800 (Spawned) - Coast Way (S of Friendly Arm Inn, destroyed caravan)",
	"bg2800 - Coast Way (S of Friendly Arm Inn, destroyed caravan)",
	"bg2900 (Spawned) - Larswood (Teven, Osmadi, Corsone)",
	"bg2900 - Larswood (Teven, Osmadi, Corsone)",
	"bg3000 - Spider Wood (E of Larswood, Thayvian Red Wizards)",
	"bg3100 - Shipwreck's Coast (S of Candlekeep, Shoal, Droth, Mad Arcand, Surgeon)",
	"bg3200 - High Hedge, exterior (Kivan)",
	"bg3202 - High Hedge, interior (Thalantyr)",
	"bg3300 (Spawned) - Beregost (Garrick, Jovial Juggler, Feldepost's Inn, Burning Wizard, Red Sheaf))",
	"bg3300 - Beregost (Garrick, Jovial Juggler, Feldepost's Inn, Burning Wizard, Red Sheaf))",
	"bg3304 - Jovial Juggler, ground floor (Bjornin, Gurke)",
	"bg3313 - Mirianne's home, ground floor",
	"bg3320 - Travenhurst Manor, ground floor",
	"bg3327 - Generic home, ground floor",
	"bg3333 - Firebeard Elvenhair's home, ground floor",
	"bg3351 - Feldepost's Inn, ground floor (Marl)",
	"bg3352 (Spawned) - Feldepost's Inn, second floor (Algernon)",
	"bg3352 - Feldepost's Inn, second floor (Algernon)",
	"bg3357 - Red Sheaf, ground floor (Perdue)",
	"bg3400 - Beregost Temple, exterior (Cattack)",
	"bg3402 - Beregost Temple, interior (AKA Song of the Morning, Keldath Ormlyr)",
	"bg3500 - Mutamin's Garden (Shar-Teel, Mutamin, Korax, basilisks, Tamah)",
	"bg3600 - Lighthouse (Safana, Ardrouine, Sil)",
	"bg3700 - Red Canyons (Bassilus, Melicamp)",
	"bg3800 - South Beregost Road",
	"bg3900 - Ulcaster School, exterior (Ulcaster, Icharyd)",
	"bg4000 - Gullykin, exterior",
	"bg4003 - Temple of Yondalla, ground floor",
	"bg4007 - Generic home, ground floor",
	"bg4011 - Generic home, ground floor",
	"bg4100 - Archaeological Site, exterior (Brage, Charleston Nib, Doomsayer)",
	"bg4200 - Fisherman's Lake (Drizzt. Bjornin's half-ogres)",
	"bg4400 - Lonely Peaks (Hulrik and Arabelle, Sarhedra, Arghain)",
	"bg4500 - Firewine Bridge (Kahrk, Carsa, Poe, Bentan, Melium)",
	"bg4600 - Bear River (N of Gnoll Stronghold, Larel, Nevill, Jared)",
	"bg4700 - Xvart Village (Nexlit, Ursa, Borda)",
	"bg4800 (Spawned) - Nashkel (Minsc, Edwin, Berrun Ghastkill, Belching Dragon, Temple of Helm)",
	"bg4800 - Nashkel (Minsc, Edwin, Berrun Ghastkill, Belching Dragon, Temple of Helm)",
	"bg4801 - Nashkel Inn",
	"bg4803 - Nashkel Store",
	"bg4809 - Belching Dragon Tavern (Volo)",
	"bg4810 - Nashkel barracks",
	"bg4900 - Nashkel Carnival (Branwen, Great Gazib)",
	"bg4901 - Small carnival tent (armor merchant)",
	"bg4903 - Large carnival tent (Vitiare)",
	"bg4905 - Small carnival tent (rare potions merchant)",
	"bg4906 - Small carnival tent (Zordral and Bentha)",
	"bg4908 - Small carnival tent (melee weapons merchant)",
	"bg4909 - Small carnival tent (ranged weapons merchant)",
	"bg5000 - Valley of the Tombs (Nashkel mines exit, Narcillicus, Hentold)",
	"bg5100 - Gnoll Stronghold (Dynaheir)",
	"bg5200 - Dryad Falls (Cloudpeak Dryad, Drienne, Ingot, Krumm, Caldo)",
	"bg5201 - Firewine Ruins (Lendarn, ogre mage, undead knights)",
	"bg5300 - Fire Leaf Forest (S of Nashkel, Albert, Rufie, Vax, Sendai)",
	"bg5400 - Nashkel Mines, exterior (Prism)",
	"bg5401 - Nashkel Mines, first subterranean level (Dink)",
	"bg5402 - Nashkel Mines, second subterranean level (Kylee, Beldin)",
	"bg5405 - Nashkel Mines, Mulahey's lair (Xan, Mulahey)",
	"bg5500 (Spawned) - Gibberling Mountains (Samuel, Hafiz)",
	"bg5500 - Gibberling Mountains (Samuel, Hafiz)",
	"bg5506 - Candlekeep Caves (Diarmid, Prat, Sakul, Tam, Bor)",
	"bg5600 (Spawned) - Random encounter area",
	"bg5601 (Spawned) - Random encounter area",
	"bg5700 (Spawned) - Random encounter area",
	"bg5701 (Spawned) - Random encounter area",
	"bg5710 - Unused",
	"bg5800 (Spawned) - Random encounter area",
	"bg5801 (Spawned) - Random encounter area",
	"bg5900 (Spawned) - Random encounter area",
	"bg5901 (Spawned) - Random encounter area",
	"bg6000 (Spawned) - Random encounter area",
	"bg6001 (Spawned) - Random encounter area",
	"bg6100 (Spawned) - Random encounter area",
	"bphub (Spawned)",
	"c6fledg2 (Spawned)",
	"c6spwn1 (Spawned)",
	"c6spwn2 (Spawned)",
	"c6spwn3 (Spawned)",
	"c6spwn4 (Spawned)",
	"c6spwn5 (Spawned)",
	"c6tanov (Spawned)",
	"cernd (Spawned)",
	"ch1cut01 (Spawned)",
	"colette (Spawned)",
	"cut01 (Spawned)",
	"cut05a (Spawned)",
	"cut12a (Spawned)",
	"cut17b (Spawned)",
	"cut204f (Spawned)",
	"cut204f2 (Spawned)",
	"cut204f3 (Spawned)",
	"cut204f4 (Spawned)",
	"cut205b (Spawned)",
	"cut207a (Spawned)",
	"cut21b (Spawned)",
	"cut236a (Spawned)",
	"cut236b (Spawned)",
	"cut237a (Spawned)",
	"cut239a (Spawned)",
	"cut23a (Spawned)",
	"cut240a (Spawned)",
	"cut241a (Spawned)",
	"cut242a (Spawned)",
	"cut243b (Spawned)",
	"cut243c (Spawned)",
	"cut26a (Spawned)",
	"cut26b (Spawned)",
	"cut31a (Spawned)",
	"cut31g (Spawned)",
	"cut31l (Spawned)",
	"cut31q (Spawned)",
	"cut31r (Spawned)",
	"cut32c (Spawned)",
	"cut32d (Spawned)",
	"cut32e (Spawned)",
	"cut32e2 (Spawned)",
	"cut32h (Spawned)",
	"cut32i (Spawned)",
	"cut32j (Spawned)",
	"cut32k (Spawned)",
	"cut33a (Spawned)",
	"cut33b (Spawned)",
	"cut35k (Spawned)",
	"cut35l (Spawned)",
	"cut36a (Spawned)",
	"cut37a (Spawned)",
	"cut38a (Spawned)",
	"cut39a (Spawned)",
	"cut39b (Spawned)",
	"cut40b (Spawned)",
	"cut41b (Spawned)",
	"cut41d (Spawned)",
	"cut41o (Spawned)",
	"cut41r (Spawned)",
	"cut41y (Spawned)",
	"cut41z (Spawned)",
	"cut41za (Spawned)",
	"cut41ze (Spawned)",
	"cut41zg (Spawned)",
	"cut51a (Spawned)",
	"cut60b (Spawned)",
	"cut80a (Spawned)",
	"cut80b (Spawned)",
	"cut80c (Spawned)",
	"cut80d (Spawned)",
	"cut80e (Spawned)",
	"cut80f (Spawned)",
	"cut81a (Spawned)",
	"cut81b (Spawned)",
	"cut81c (Spawned)",
	"cut81d (Spawned)",
	"cut81e (Spawned)",
	"cut81f (Spawned)",
	"cut82a (Spawned)",
	"cut82b (Spawned)",
	"cut82c (Spawned)",
	"cut82d (Spawned)",
	"cut82e (Spawned)",
	"cut82f (Spawned)",
	"cut82g (Spawned)",
	"cut87a (Spawned)",
	"cutamk01 (Spawned)",
	"cutba01 (Spawned)",
	"cutd1 (Spawned)",
	"cutmove1 (Spawned)",
	"cutne0a (Spawned)",
	"cutskip (Spawned)",
	"cutskip1 (Spawned)",
	"dadrow5 (Spawned)",
	"digcut01 (Spawned)",
	"dw#taug (Spawned)",
	"dwdoor01 (Spawned)",
	"dwface02 (Spawned)",
	"dwface03 (Spawned)",
	"dwface04 (Spawned)",
	"dwface06 (Spawned)",
	"dwtalk1 (Spawned)",
	"edwin (Spawned)",
	"explore (Spawned)",
	"gaalsht (Spawned)",
	"gartrig (Spawned)",
	"githspwn (Spawned)",
	"grave (Spawned)",
	"hashout (Spawned)",
	"hdmurd (Spawned)",
	"jaheira (Spawned)",
	"jan (Spawned)",
	"mazzy (Spawned)",
	"merch2 (Spawned)",
	"merch4 (Spawned)",
	"merch5 (Spawned)",
	"merch6 (Spawned)",
	"mercha (Spawned)",
	"movie02b (Spawned)",
	"movie05b (Spawned)",
	"mvally (Spawned)",
	"mysmer (Spawned)",
	"nalia (Spawned)",
	"narcut (Spawned)",
	"newgame (Spawned)",
	"oh1000 (Spawned) - Dorn - Random Encounter Area",
	"oh2000 - Neera - Adoy's Enclave, exterior",
	"oh2010 (Spawned) - Neera - Adoy's Enclave, interior",
	"oh2010 - Neera - Adoy's Enclave, interior",
	"oh3000 - Rasaad - Dark Moon temple, exterior",
	"oh3010 - Rasaad - Dark Moon temple, interior",
	"oh3100 - Rasaad - Dark Moon temple, interior",
	"oh4000 - Rasaad - The Amphitheater",
	"oh4010 - Rasaad - Tears of Selune battle encounter",
	"oh4100 (Spawned) - Rasaad - Dark Moon Heretic Temple",
	"oh4100 - Rasaad - Dark Moon Heretic Temple",
	"oh4101 (Spawned) - Rasaad - Dark Moon Heretic Temple Interior",
	"oh4200 - Rasaad - Dwarven Clanhold Exterior",
	"oh4210 - Rasaad - Dwarven Clanhold Interior",
	"oh4220 (Spawned) - Rasaad - Dwarven Mines",
	"oh4220 - Rasaad - Dwarven Mines",
	"oh5000 - Dorn - Radiant Heart (Wedding)",
	"oh5200 (Spawned) - Dorn - Resurrection Gorge Interior",
	"oh5300 (Spawned) - Dorn - Helmite Camp",
	"oh5300 - Dorn - Helmite Camp",
	"oh5400 (Spawned) - Dorn - Forest Clearing",
	"oh5500 (Spawned) - Dorn - Lunia",
	"oh5500 - Dorn - Lunia",
	"oh6000 - Neera - The Wild Forest",
	"oh6100 - Neera - The Hidden Refuge",
	"oh6200 (Spawned) - Neera - The Hidden Refuge (Destroyed)",
	"oh6200 - Neera - The Hidden Refuge (Destroyed)",
	"oh6300 (Spawned) - Neera - Red Wizard Enclave",
	"oh6300 - Neera - Red Wizard Enclave",
	"oh6450 - Neera - The Black Pits: Arena",
	"oh6460 - Neera - The Black Pits: Staging Area",
	"oh6500 (Spawned) - Neera - Thayan Estate",
	"oh6500 - Neera - Thayan Estate",
	"oh7000 - Hexxat - Top Left Quarter (Dragomir)",
	"oh7100 - Hexxat - Bottom Left Quarter (Shou Lung)",
	"oh7200 (Spawned) - Hexxat - Bottom Right Quarter (Zakhara)",
	"oh7200 - Hexxat - Bottom Right Quarter (Zakhara)",
	"oh7300 - Hexxat - Completed Maze (Korkorran)",
	"oh8000 (Spawned) - TBP2 - Suzail Tavern",
	"oh8100 - TBP2 - Staging Area Map",
	"oh9310 (Spawned) - The Black Pits: Arena 1",
	"ohb_501 (Spawned)",
	"ohb_502 (Spawned)",
	"ohbare1 (Spawned)",
	"ohbare2 (Spawned)",
	"ohbcut00 (Spawned)",
	"ohbcut08 (Spawned)",
	"ohbcut13 (Spawned)",
	"ohbcut17 (Spawned)",
	"ohbcut20 (Spawned)",
	"ohbcut24 (Spawned)",
	"ohbhub (Spawned)",
	"ohbpost (Spawned)",
	"ohdcut04 (Spawned)",
	"ohdcut07 (Spawned)",
	"ohdcut12 (Spawned)",
	"ohdlugen (Spawned)",
	"ohdwra01 (Spawned)",
	"ohdyarrg (Spawned)",
	"ohhcab25 (Spawned)",
	"ohhphrey (Spawned)",
	"ohhwra01 (Spawned)",
	"ohncut02 (Spawned)",
	"ohncut05 (Spawned)",
	"ohncut12 (Spawned)",
	"ohncut15 (Spawned)",
	"ohncut16 (Spawned)",
	"ohnmcut1 (Spawned)",
	"ohrambus (Spawned)",
	"ohrcut4y (Spawned)",
	"ppalt (Spawned)",
	"ptalarm1 (Spawned)",
	"rasaad_ (Spawned)",
	"resimo2 (Spawned)",
	"sahorb (Spawned)",
	"sarevok_ (Spawned)",
	"scarcut (Spawned)",
	"sharkamb (Spawned)",
	"shopkn (Spawned)",
	"shthass1 (Spawned)",
	"slaver2 (Spawned)",
	"suscene1 (Spawned)",
	"suscene3 (Spawned)",
	"suscene4 (Spawned)",
	"tbullrsh (Spawned)",
	"titach (Spawned)",
	"tmeiala (Spawned)",
	"trrak01 (Spawned)",
	"udsoltri (Spawned)",
	"und5509 (Spawned)",
	"unknown",
	"vampsttp (Spawned)",
]

types = {
	"Amulet": [
		"Amulet of Power",
		"Amulet of Protection +1",
		"Amulet of Protection +2",
		"Amulet of Spell Warding",
		"Amulet of the Keeper of Secrets Under the Mountain",
		"Arkion's Bloodstone Amulet",
		"Bloodstone Amulet",
		"Galvena's Medallion",
		"Gold Necklace",
		"Greenstone Amulet",
		"Kaligun's Amulet of Magic Resistance",
		"Keepsake Locket",
		"Laeral's Tear Necklace",
		"Lon's Amulet",
		"Necklace of Form Stability",
		"Necklace of Talos",
		"Pearl Necklace",
		"Periapt of Proof Against Poison",
		"Rainbow Obsidian Necklace",
		"Ruby Pendant of Beguiling",
		"Shield Amulet",
		"Sigil of Tyr",
		"Silver Necklace",
		"The Amplifier",
		"The One Gift Lost",
		"The Protector +1",
		"Thrall Collar",
	],
	"Armor": [
		"Adventurer's Robe",
		"Ankheg Plate Mail",
		"Chain Mail +1",
		"Chain Mail +2",
		"Chain Mail Armor",
		"Full Plate Mail",
		"Full Plate Mail +1",
		"Hide Armor",
		"Hide Armor +1",
		"Knave's Robe",
		"Leather Armor",
		"Leather Armor +1",
		"Leather Armor +2",
		"Leather Armor +3",
		"Mage Robe of Cold Resistance",
		"Mage Robe of Electric Resistance",
		"Mage Robe of Fire Resistance",
		"Plate Mail",
		"Plate Mail +1",
		"Robe of the Evil Archmagi",
		"Robe of the Good Archmagi",
		"Robe of the Neutral Archmagi",
		"Skin of the Ghoul +4",
		"Splint Mail",
		"Splint Mail +1",
		"Studded Leather Armor",
		"Studded Leather Armor +1",
		"Studded Leather Armor +2",
		"Traveler's Robe",
	],
	"Arrows": [
		"Acid Arrow +1",
		"Arrow",
		"Arrow +1",
		"Arrow +2",
		"Arrow +3",
		"Arrow of Biting",
		"Arrow of Detonation",
		"Arrow of Dispelling",
		"Arrow of Fire",
		"Arrow of Ice",
		"Arrow of Piercing +1",
		"Flaming Arrow",
	],
	"Axe": [
		"Azuredge +3",
		"Battle Axe",
		"Battle Axe +1",
		"Battle Axe +2",
		"Battle Axe +3",
		"Hangard's Axe +2",
		"Stonefire +3",
		"Throwing Axe",
		"Throwing Axe +2",
	],
	"Belt & Girdle": [
		"Adoy's Belt",
		"Belt of Antipode",
		"Belt of Inertial Barrier",
		"Belt of the Cunning Rogue",
		"Cloverleaf",
		"Destroyer of the Hills",
		"Elves' Bane",
		"Girdle of Bluntness",
		"Girdle of Fortitude",
		"Girdle of Hill Giant Strength",
		"Girdle of Piercing",
		"Golden Girdle",
		"Golden Girdle of Urnst",
	],
	"Bolts": [
		"Bolt",
		"Bolt +1",
		"Bolt +2",
		"Bolt +3",
		"Bolt of Biting ",
		"Bolt of Lightning",
		"Case of Plenty +1",
		"Drow Bolt +1",
		"Drow Bolt of Sleep",
		"Drow Bolt of Stunning",
		"Flasher Master Bruiser Mate",
		"Kuo-toan Bolt",
		"Paralytic Bolt",
	],
	"Books & misc": [
		"Acorn of Yarrow",
		"Acorns",
		"Aerie's Body",
		"Ancient Armor",
		"Anomen's Body",
		"Barrel of Bwoosh!",
		"Bassilus's Holy Symbol",
		"Black Spider Figurine",
		"Book of Infinite Spells",
		"Bowl of Water Elemental Control",
		"Bowstring of Gond",
		"Demon Heart",
		"Dennis's Mother's Gong",
		"Draconis's Head",
		"Dradeel's Spellbook",
		"Edwin's Documents",
		"Efreeti Bottle",
		"Elven Holy Water",
		"Exotic Hide",
		"Farthing's Dolly",
		"Fil's Summoning Stone",
		"Flail Head (Acid)",
		"Gem of Seeing",
		"Ghost Jar",
		"Glasses of Identification",
		"Golden Goblet",
		"Golden Pantaloons",
		"Guril Berries",
		"Hindo's Hand",
		"Illithium Ore",
		"Ink and Sand",
		"Jae'llat Wardstone",
		"Jaheira's Body",
		"Journal of Umolex the Far-Eyed",
		"Keherrem's Badge",
		"Key to River Plug",
		"Light Gem",
		"Littleman the Stuffed Bear",
		"Magical Rope",
		"Meems's Special Grog",
		"Mekrath's Mirror",
		"Mug of Ale",
		"Mulahey's Holy Symbol",
		"Myconid Bloom-Sac",
		"Note",
		"Oak Bark",
		"Peladan",
		"Piece of Red Cloth",
		"Qilue's Brain",
		"RNDARO01.itm (TLK missing name)",
		"RNDGEM01.itm (TLK missing name)",
		"RNDGEM02.itm (TLK missing name)",
		"RNDGEM03.itm (TLK missing name)",
		"RNDMAG01.itm (TLK missing name)",
		"RNDMAG06.itm (TLK missing name)",
		"RNDPTN01.itm (TLK missing name)",
		"RNDSCR01.itm (TLK missing name)",
		"RNDSCR04.itm (TLK missing name)",
		"RNDTRE01.ITM (TLK missing name)",
		"RNDTRE02.ITM (TLK missing name)",
		"RNDTRE03.ITM (TLK missing name)",
		"RNDTRE04.ITM (TLK missing name)",
		"RNDTRE05.ITM (TLK missing name)",
		"RNDTRE06.itm (TLK missing name)",
		"RNDTRE07.itm (TLK missing name)",
		"RNDTRE08.itm (TLK missing name)",
		"RNDTRE09.itm (TLK missing name)",
		"RNDTRI02.itm (TLK missing name)",
		"RNDWAND.itm (TLK missing name)",
		"Rebel's Orb",
		"Rope",
		"SODTRE09.itm (TLK missing name)",
		"Sea Charts",
		"Seal of Caelar",
		"Second Stone Fragment",
		"Shakti Figurine",
		"Silver Hilt",
		"Silver Pantaloons",
		"Smuggled Shipment",
		"Solik Berries",
		"Stone Ally",
		"Tears of Bhaal",
		"The Genie's Flask",
		"The Journal of Saemon Havarian",
		"Token of Faith",
		"Tome of Understanding",
		"Viconia's Body",
		"Wardstone",
		"Wardstone for Asylum",
		"Wave Blade",
		"Wooden Stake",
		"Xachrimos's Summoning Stone",
	],
	"Books/Broken shields/bracelets": [
		"Book of Rituals",
		"Bounty Notice",
		"Deed to the Windspear Hills",
		"History of Tethyr",
		"History of the Dead Three",
		"History of the Fateful Coin",
		"History of the Last March of the Giants",
		"History of the Nether Scrolls",
		"Isaea's Slavery Document",
		"Lellyn's Journal",
		"Note",
		"Scrap of Paper",
		"Scroll of Reversal",
		"The Book of Kaza",
		"The Diary of Sarevok",
		"The Journal of Geldorf Tinbasher",
		"Worn Pamphlet",
		"Yago's Book of Curses",
	],
	"Boots": [
		"Talos's Gift",
		"The Frost's Embrace",
		"The Paws of the Cheetah",
		"Worn Whispers",
	],
	"Bow": [
		"Composite Longbow",
		"Composite Longbow +1",
		"Composite Longbow +2",
		"Composite Longbow +3",
		"Longbow",
		"Longbow +1",
		"Longbow +2",
		"Longbow +3",
		"Savage Shortbow +2",
		"Shortbow",
		"Shortbow +1",
		"Shortbow +2",
		"Shortbow +3",
		"Tansheron's Bow +3",
	],
	"Bracers & gauntlets": [
		"Bracers",
		"Bracers of Defense AC 5",
		"Bracers of Defense AC 6",
		"Bracers of Defense AC 7",
		"Bracers of Defense AC 8",
		"Bracers of the Shuttered Lid",
		"Bracers to the Death",
		"Elander's Gloves of Misplacement",
		"Gauntlets of Aln Zekk",
		"Gauntlets of Weapon Expertise",
		"Gauntlets of Weapon Skill",
		"Glimmering Bands",
		"Gloves of Missile Snaring",
		"Hands of Takkok",
		"Jansen Techno-Gloves",
		"Legacy of the Masters",
		"Nimblefinger Gloves",
		"The Brawling Hands",
		"The Dale's Protector",
		"Xarrnous's Second Sword Arm",
	],
	"Bullets": [
		"Bullet",
		"Bullet +1",
		"Bullet +2",
		"Bullet +3",
		"Bullet +4",
		"Bullet of Electricity +1",
		"Bullet of Fire +1",
		"Bullet of Ice +1",
		"Sunstone Bullet +1",
	],
	"Cloaks & Robes": [
		"Algernon's Cloak",
		"Cloak of Atonement",
		"Cloak of Balduran",
		"Cloak of Displacement",
		"Cloak of Dragomir",
		"Cloak of Minor Arcana",
		"Cloak of Mirroring",
		"Cloak of Protection +1",
		"Cloak of the High Forest +1",
		"Cloak of the Shield",
		"Cloak of the Stars",
		"Cowl of the Stars",
		"Drow Piwafwi Cloak",
		"Nymph Cloak",
		"Relair's Mistake",
		"Shadow Thief Cloak",
		"Shandalar's Cloak",
		"The Spirit's Shield +2",
		"Whispers of Silence",
	],
	"Containers/eye/broken armor": [
		"Bag of Holding",
		"Gem Bag",
		"Potion Case",
		"Scroll Case",
	],
	"Crossbow": [
		"Drow Crossbow of Speed +3",
		"Flasher Launcher",
		"Heavy Crossbow",
		"Heavy Crossbow +1",
		"Heavy Crossbow +2",
		"Heavy Crossbow +3",
		"Light Crossbow",
		"Light Crossbow +1",
		"Light Crossbow +2",
		"Light Crossbow +3",
		"The Army Scythe +1",
	],
	"Dagger": [
		"Boneblade +4",
		"Boomerang Dagger +2",
		"Dagger",
		"Dagger +1",
		"Dagger +2",
		"Dagger +3",
		"Firetooth +3",
		"Heart of the Golem +2",
		"Ixil's Spike",
		"Kylee's Dagger",
		"Poisoned Throwing Dagger",
		"Shadow Thief Dagger",
		"Throwing Dagger",
		"Throwing Dagger +1",
	],
	"Darts": [
		"Asp's Nest +1",
		"Dart",
		"Dart +1",
		"Dart of Acid +1",
		"Dart of Fire +1",
		"Dart of Ice +1",
		"Dart of Stunning",
		"Dart of Wounding",
	],
	"Drinks (IWD)": [
		"Empty Wineskin",
		"Wilhelmina's Miracle Turnip Juice",
	],
	"Flail": [
		"Drow Flail +3",
		"Flail",
		"Flail +1",
		"Flail +2",
		"Flail +3",
	],
	"Food": [
		"Good Berry",
	],
	"Gem": [
		"Andar Gem",
		"Aquamarine Gem",
		"Black Opal",
		"Bloodstone Gem",
		"Chrysoberyl Gem",
		"Diamond",
		"Dwarven Rune Wardstone",
		"Emerald",
		"Fire Agate Gem",
		"Garnet Gem",
		"Horn Coral Gem",
		"Iol Gem",
		"Jasper Gem",
		"King's Tears",
		"Lynx Eye Gem",
		"Moonbar Gem",
		"Moonstone Gem",
		"Pearl",
		"Rogue Stone",
		"Scepter Gem",
		"Shandon Gem",
		"Skydrop Gem",
		"Sphene Gem",
		"Star Diopside Gem",
		"Sunstone Gem",
		"Tchazar Gem",
		"Turquoise Gem",
		"Wardstone Forgery",
		"Water Opal",
		"Waterstar Gem",
		"Ziose Gem",
	],
	"Halberd": [
		"Halberd",
		"Halberd +1",
		"Halberd +2",
		"Halberd +3",
		"Suryris's Blade +2",
	],
	"Hammer": [
		"Aegis-fang +3",
		"Dwarven Thrower +3",
		"The Kneecapper +1",
		"War Hammer",
		"War Hammer +1",
		"War Hammer +2",
		"War Hammer +3",
	],
	"Hat": [
		"Wizzard Hat",
	],
	"Headgear": [
		"Battle Tankard",
		"Circlet of Netheril",
		"Dusty Rose Ioun Stone",
		"Golden Ioun Stone",
		"Helm of the Noble +1",
		"Helmet",
		"Lavender Ioun Stone",
		"Obsidian Ioun Stone",
		"Purification Stone",
		"Roranach's Horn",
		"Silver Ioun Stone",
	],
	"Key": [
		"Beastmaster Key",
		"Branson's Key",
		"Drawbridge Key",
		"Firkraag Prison Key",
		"Guild House Key",
		"Haegan's Key",
		"Holding Pen Key",
		"Intricate Key",
		"Jail Key",
		"Key",
		"Key of Scholars",
		"Key of the Master's Crypt",
		"Korlasz's Key",
		"Monastery Gate Key",
		"Piece of Burial Mask",
		"Portal Key",
		"Ritual Room Key",
		"Sahuagin Treasury Key",
		"Secret Jail Door Key",
		"Sewage Golem Key",
		"Shadow Prison Key",
		"Shadow Thief Prison Key",
		"Slave Pen Key",
		"Temple Key",
		"Tomb Key",
		"Wand of Missiles Key",
	],
	"Large sword": [
		"Abyssal Blade",
		"Bastard Sword",
		"Bastard Sword +1",
		"Bastard Sword +2",
		"Bastard Sword +3",
		"Blackrazor +3",
		"Blade of Roses +3",
		"Dervish Crescent +2",
		"Drow Long Sword +3",
		"Eadro's Blade +1",
		"Gold Digger +1",
		"Harbinger +3",
		"Hawksight +2",
		"Holy Long Sword of Tyr +3",
		"Katana",
		"Katana +1",
		"Katana +2",
		"Katana +3",
		"Long Sword",
		"Long Sword +1",
		"Long Sword +2",
		"Long Sword +3",
		"Ninja-To",
		"Ninja-To +1",
		"Ras, The Dancing Blade +2",
		"Scimitar",
		"Scimitar +1",
		"Scimitar +3",
		"Sword of Flame +1",
		"The Burning Earth +1",
		"The Ogre's Sword",
		"Twinkle +3",
		"Two-handed Sword",
		"Two-handed Sword +1",
		"Two-handed Sword +2",
		"Two-handed Sword +3",
		"Varscona +2",
	],
	"Mace & Club": [
		"Blackblood +3",
		"Club",
		"Club +1",
		"Club +3",
		"Cudgel of Montgomer +1",
		"Mace",
		"Mace +1",
		"Mace +2",
		"Mace +3",
		"Mauler's Arm +2",
		"Mosela's Cudgel +2",
	],
	"Morning star": [
		"Morning Star",
		"Morning Star +1",
		"Morning Star +2",
		"Morning Star +3",
		"The Sleeper +2",
	],
	"Potion": [
		"Agathor's Near-Universal Solvent",
		"Antidote",
		"Bottle of Wine",
		"De'Tranion's Baalor Ale",
		"Elixir of Health",
		"Empty Breath Potion Flask",
		"Marek's Potion of Antidote",
		"Oil of Fiery Burning",
		"Oil of Speed",
		"Potion of Absorption",
		"Potion of Agility",
		"Potion of Clairvoyance",
		"Potion of Clarity",
		"Potion of Cloud Giant Strength",
		"Potion of Cold Resistance",
		"Potion of Defense",
		"Potion of Explosions",
		"Potion of Extra Healing",
		"Potion of Fire Breath",
		"Potion of Fire Giant Strength",
		"Potion of Fire Resistance",
		"Potion of Fortitude",
		"Potion of Freedom",
		"Potion of Frost Giant Strength",
		"Potion of Genius",
		"Potion of Healing",
		"Potion of Heroism",
		"Potion of Hill Giant Strength",
		"Potion of Infravision",
		"Potion of Insight",
		"Potion of Insulation",
		"Potion of Invisibility",
		"Potion of Invulnerability",
		"Potion of Magic Blocking",
		"Potion of Magic Protection",
		"Potion of Magic Shielding",
		"Potion of Master Thievery",
		"Potion of Mind Focusing",
		"Potion of Mirrored Eyes",
		"Potion of Perception",
		"Potion of Persuasiveness",
		"Potion of Power",
		"Potion of Regeneration",
		"Potion of Stone Form",
		"Potion of Stone Giant Strength",
		"Potion of Storm Giant Strength",
		"Potion of Strength",
		"Potion of Superior Healing",
		"Red Potion",
		"Slime Sickness Curative",
		"Speedily Stolen Slaves' Salve",
		"Violet Potion",
	],
	"Quarterstaff": [
		"Cleric's Staff +3",
		"Martial Staff +3",
		"Neera's Staff +1",
		"Quarterstaff",
		"Quarterstaff +1",
		"Quarterstaff +2",
		"Quarterstaff +3",
		"Rod of Smiting",
		"Rod of Terror",
		"Staff Mace +2",
		"Staff Spear +2",
		"Staff of Earth +2",
		"Staff of Striking +3",
		"The Ossifier",
	],
	"Ring": [
		"Angel Skin Ring",
		"Batalista's Passport",
		"Bloodstone Ring",
		"Dal Family Ring",
		"Dawn Ring",
		"Discipliner",
		"Dreon's Signet Ring",
		"Druid's Ring",
		"Edventar's Gift",
		"Evermemory",
		"Fire Opal Ring",
		"Flamedance Ring",
		"Gold Ring",
		"Honorary Ring of Sune",
		"Jade Ring",
		"Koveras's Ring of Protection",
		"Nemphre's Onyx Ring",
		"Oaken Ring",
		"Onyx Ring",
		"Ring",
		"Ring of Acuity",
		"Ring of Anti-Venom",
		"Ring of Fire Control",
		"Ring of Fire Resistance",
		"Ring of Free Action",
		"Ring of Human Influence",
		"Ring of Lock Picks",
		"Ring of Protection +1",
		"Ring of Purity",
		"Ring of Regeneration",
		"Ring of Spell Turning",
		"Ring of Wizardry",
		"Ring of the Princes +1",
		"Ring of the Ram",
		"Ruby Ring",
		"SWORDI.ITM (TLK missing name)",
		"Sandthief's Ring",
		"Sashenstar's Ruby Ring",
		"Silver Ring",
		"The Guard's Ring +2",
		"The Jester's Folly",
		"The Victor",
		"Topsider's Crutch",
	],
	"Scroll": [
		"Abi-Dalzim's Horrid Wilting",
		"Absolute Immunity",
		"Agannazar's Scorcher",
		"Andris's Journal",
		"Animate Dead",
		"Armor",
		"Bigby's Clenched Fist",
		"Bigby's Crushing Hand",
		"Black Blade of Disaster",
		"Black Pits Flyer",
		"Blindness",
		"Blur",
		"Breach",
		"Burning Hands",
		"Cacofiend",
		"Carrion Summons",
		"Chain Contingency",
		"Chain Lightning",
		"Chaos",
		"Chaotic Commands",
		"Charm Person",
		"Chill Touch",
		"Chromatic Orb",
		"Clairvoyance",
		"Cloudkill",
		"Color Spray",
		"Cone of Cold",
		"Confusion",
		"Conjure Air Elemental",
		"Conjure Earth Elemental",
		"Conjure Fire Elemental",
		"Conjure Lesser Air Elemental",
		"Conjure Lesser Earth Elemental",
		"Conjure Lesser Fire Elemental",
		"Contact's Note",
		"Contagion",
		"Contingency",
		"Control Undead",
		"Cure Critical Wounds",
		"Cure Serious Wounds",
		"Cursed Scroll of Ailment",
		"Cursed Scroll of Clumsiness",
		"Cursed Scroll of Foolishness",
		"Cursed Scroll of Petrification",
		"Cursed Scroll of Stupidity",
		"Cursed Scroll of Summon Monster",
		"Cursed Scroll of Ugliness",
		"Cursed Scroll of Weakness",
		"Dark Moon Note",
		"Deafness",
		"Death Fog",
		"Death Spell",
		"Delayed Blast Fireball",
		"Demin's Note",
		"Detect Evil",
		"Detect Illusion",
		"Detect Invisibility",
		"Dezkiel's Scroll",
		"Dire Charm",
		"Disintegrate",
		"Dispel Magic",
		"Domination",
		"Emotion: Hopelessness",
		"Enchanted Weapon",
		"Energy Drain",
		"Farsight",
		"Feeblemind",
		"Find Familiar",
		"Finger of Death",
		"Fireball",
		"Fireshield (Blue)",
		"Fireshield (Red)",
		"Flame Arrow",
		"Flesh to Stone",
		"Free Action",
		"Freedom",
		"Friends",
		"Gate",
		"Geas Removal Scroll",
		"Ghost Armor",
		"Ghoul Touch",
		"Glitterdust",
		"Globe of Invulnerability",
		"Grease",
		"Greater Malison",
		"Haste",
		"Hold Monster",
		"Hold Person",
		"Hold Undead",
		"Horror",
		"Ice Storm",
		"Identify",
		"Immunity: Abjuration",
		"Immunity: Alteration",
		"Immunity: Conjuration",
		"Immunity: Divination",
		"Immunity: Enchantment",
		"Immunity: Evocation",
		"Immunity: Illusion",
		"Immunity: Necromancy",
		"Imprisonment",
		"Improved Haste",
		"Improved Invisibility",
		"Improved Mantle",
		"Incendiary Cloud",
		"Infravision",
		"Invisibility",
		"Invisibility, 10' Radius",
		"Invisible Stalker",
		"Invitation",
		"Khelben's Warding Whip",
		"Knock",
		"Know Alignment",
		"Larloch's Minor Drain",
		"Letter",
		"Letter to Kryll",
		"Lightning Bolt",
		"Limited Wish",
		"Lower Resistance",
		"Luck",
		"Magic Missile",
		"Mantle",
		"Mass Invisibility",
		"Maze",
		"Melf's Acid Arrow",
		"Melf's Minute Meteors",
		"Meteor Swarm",
		"Minor Globe of Invulnerability",
		"Minor Sequencer",
		"Minor Spell Deflection",
		"Minor Spell Turning",
		"Mirror Image",
		"Mislead",
		"Monster Summoning I",
		"Monster Summoning II",
		"Monster Summoning III",
		"Mordenkainen's Sword",
		"Neutralize Poison",
		"Non-Detection",
		"Note",
		"Oracle",
		"Otiluke's Resilient Sphere",
		"Phantom Blade",
		"Pierce Magic",
		"Pierce Shield",
		"Polymorph Other",
		"Polymorph Self",
		"Power Word, Blind",
		"Power Word, Kill",
		"Power Word, Silence",
		"Power Word, Sleep",
		"Power Word, Stun",
		"Prismatic Spray",
		"Project Image",
		"Protection From Acid",
		"Protection From Cold",
		"Protection From Electricity",
		"Protection From Energy",
		"Protection From Evil",
		"Protection From Fire",
		"Protection From Magic",
		"Protection From Magic Energy",
		"Protection From Magical Weapons",
		"Protection From Normal Missiles",
		"Protection From Normal Weapons",
		"Protection From Petrification",
		"Protection From Poison",
		"Protection From The Elements",
		"Protection From Undead",
		"Raise Dead",
		"Ray of Enfeeblement",
		"Reflected Image",
		"Remove Curse",
		"Remove Magic",
		"Resist Fear",
		"Restoration",
		"Ruby Ray of Reversal",
		"Scroll",
		"Secret Word",
		"Seditious Letter",
		"Shadow Door",
		"Shapechange",
		"Shield",
		"Shocking Grasp",
		"Simulacrum",
		"Skull Trap",
		"Sleep",
		"Slow",
		"Sorrem's Note",
		"Spell Deflection",
		"Spell Immunity",
		"Spell Sequencer",
		"Spell Shield",
		"Spell Thrust",
		"Spell Trap",
		"Spell Trigger",
		"Spell Turning",
		"Spellstrike",
		"Sphere of Chaos",
		"Spider Spawn",
		"Spirit Armor",
		"Spook",
		"Stinking Cloud",
		"Stone to Flesh",
		"Stone to Flesh Scroll",
		"Stoneskin",
		"Strength",
		"Summon Djinni",
		"Summon Efreeti",
		"Summon Fiend",
		"Summon Hakeashar",
		"Summon Nishruu",
		"Sunfire",
		"Symbol, Death",
		"Symbol, Fear",
		"Symbol, Stun",
		"Teleport Field",
		"Tenser's Transformation",
		"Time Stop",
		"Tizzak's Journal",
		"True Sight",
		"Tsolak's Scroll",
		"Vampiric Touch",
		"Vocalize",
		"Wail of the Banshee",
		"Web",
		"Wish",
		"Wizard Eye",
		"Wraithform",
		"Wyvern Call",
	],
	"Shield": [
		"Buckler",
		"Buckler +1",
		"Large Shield",
		"Large Shield +1",
		"Large Shield +2",
		"Medium Shield",
		"Medium Shield +1",
		"Medium Shield +2",
		"Reed of Echoes",
		"Sentinel +4",
		"Small Shield",
		"Small Shield +1",
		"Small Shield +2",
		"The Suncatcher +2",
	],
	"Sling": [
		"Sling ",
		"Sling +1",
		"Sling +2",
		"Sling +3",
		"Sling of Seeking +1",
	],
	"Small sword": [
		"Short Sword",
		"Short Sword +1",
		"Short Sword +2",
		"Short Sword +3",
		"Sword of Arvoreen +2",
		"The Shadow's Blade +3",
		"The Whistling Sword +2",
		"Wakizashi",
		"Wakizashi +1",
		"Yamato +4",
	],
	"Spear": [
		"Backbiter +3",
		"Impaler +3",
		"Spear",
		"Spear +1",
		"Spear +2",
		"Spear +3",
		"Spear of Withering +4",
	],
	"Tattoos": [
		"Bandit Scalp",
	],
	"Unknown": [
		"Herdrin's Body",
		"Iron Rod",
		"Kendra's Body",
		"Lexa's Body",
	],
	"Wand": [
		"Rod of Resurrection",
		"Rod of Shadowstep",
		"Wand of Cloudkill",
		"Wand of Cursing",
		"Wand of Fear",
		"Wand of Fire",
		"Wand of Frost",
		"Wand of Lightning",
		"Wand of Magic Missiles",
		"Wand of Monster Summoning",
		"Wand of Paralyzation",
		"Wand of Polymorphing",
		"Wand of Sleep",
		"Wand of Spell Striking",
		"Wand of the Heavens",
	],
}
