gamestr = "Icewind Dale EE 2.6.5.0 + BetterHOF + CDTWEAKS"
headers = ["Area", "NPC", "XP", "Gold Carried", "Pickpocket Skill", "Item Price (base)", "Item Type", "Item"]

areas = [
	"animtest (Spawned)",
	"ar1001 - Easthaven (prologue) - Temple of Tempus",
	"ar1008 - Easthaven (prologue) - Snowdrift Inn",
	"ar1100 - Easthaven (finale)",
	"ar1101 - Easthaven (finale) - Temple of Tempus/ice tower first floor",
	"ar2003 - Kuldahar Pass - Gherg's tower",
	"ar2004 - Kuldahar Pass - Mill - entrance",
	"ar2100 (Spawned) - Kuldahar",
	"ar2102 - Kuldahar - Orrick the Grey's tower - study",
	"ar2108 - Kuldahar - Airship of Oswald Fiddlebender",
	"ar2112 - Kuldahar - Home of Arundel - first floor",
	"ar3301 - Vale of Shadows - Temple of Myrkul",
	"ar3501 - Vale of Shadows - Tomb of Kresselack - first level",
	"ar4003 - Dragon's Eye - third dungeon level (Presio)",
	"ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)",
	"ar4005 - Dragon's Eye - fifth dungeon level (Yxunomei)",
	"ar5401 - Severed Hand - Tower of Sheverash - first floor, Kaylessa",
	"ar5404 - Severed Hand - Tower of Sheverash - fourth floor",
	"ar6003 - Dorn's Deep - orog cave, Saablic, Krilag",
	"ar6014 - Dorn's Deep - Bandoth's cave",
	"ar7001 - Wyrm's Tooth Glacier - aquarium interior, ice salamander lair",
	"ar7004 - Wyrm's Tooth Glacier - frost giant cave",
	"ar8005 - Lower Dorn's Deep - Order of the Kraken garde",
	"ar8007 (Spawned) - Lower Dorn's Deep - Order of the Kraken manor - second floor, Mekrath",
	"ar8010 (Spawned) - Lower Dorn's Deep - Malavon's lair",
	"ar8010 - Lower Dorn's Deep - Malavon's lair",
	"ar8011 - Lower Dorn's Deep - forge, Ilmadia",
	"ar9100 (Spawned) - Lonelywood",
	"ar9101 - Lonelywood - Whistling Gallows - first floor",
	"ar9106 (Spawned) - Lonelywood - Thurlow home - first floor",
	"ar9107 (Spawned) - Lonelywood - Thurlow home - second floor",
	"ar9110 - Lonelywood - Home of Purvis",
	"ar9501 - Gloomfrost interior - first level, Tiernon",
	"ar9700 - Anauroch Castle - outer courtyard (TotL start area)",
	"ar9704 - Anauroch Castle - west Tower upstairs - Harald",
	"ar9706 - Anauroch Castle - north Tower upstairs - harpy queen",
	"ar9708 - Anauroch Castle - east Tower upstairs - Banites",
	"ar9715 - Anauroch Castle - hideout of Hobart",
	"unknown",
]

types = {
	"Amulet": [
		"Amulet of Metaspell Influence",
		"Amulet of Protection",
		"Great Black Wolf Talisman",
		"Kossuth's Blood",
		"Necklace of Missiles",
		"Symbol of Corellon Larethian",
		"Symbol of Solonor Thelandira",
		"Tiernon's Hearthstone",
	],
	"Armor": [
		"Chain Mail",
	],
	"Arrows": [
		"Arrow of Fire +1",
		"Arrow of the Hand +8",
	],
	"Books & misc": [
		"Maiden Ilmadia's Badge",
		"Manual of Gainful Exercise",
		"Tome of Clear Thought",
		"Tome of Leadership and Influence",
		"Tome of Understanding",
		"Umber Hulk Hide",
		"mernbook.itm ()TLK missing name)",
		"mernmanu.itm ()TLK missing name)",
		"merntome.itm ()TLK missing name)",
		"rndtre50.itm",
	],
	"Darts": [
		"Asp's Nest +1",
	],
	"Gem": [
		"Emerald",
		"Moonbar Gem",
		"Moonstone Gem",
		"Rogue Stone",
	],
	"Gold pieces": [
		"Gold Piece",
	],
	"Large sword": [
		"Bastard Sword ",
	],
	"Potion": [
		"Haste Potion",
		"Oil of Fiery Burning",
		"Oil of Speed",
		"Potion of Extra Healing",
		"Potion of Fast Casting",
		"Potion of Firebreath",
		"Potion of Healing",
		"Potion of Holy Transference",
		"Potion of Life Transference",
		"Potion of Vitality",
	],
	"Quarterstaff": [
		"The Summoner's Staff +3",
	],
	"Ring": [
		"Greater Ring of the Warrior",
		"Kontik's Ring of Wizardry",
		"Onyx Ring",
		"Ring of Aura Transfusion",
		"Ring of Fire Resistance",
		"Ring of Free Action",
		"Ring of Pain Amplification",
		"Ring of Protection +2",
		"Ring of Protection +3",
		"Ring of Protection +4",
		"Ring of Reckless Action",
		"Ring of Shadows",
		"Ring of the Warrior",
	],
	"Scroll": [
		"Blur",
		"Comet",
		"Dragon's Breath",
		"Emotion, Hope",
		"Portrait of Marketh",
		"Wail of the Banshee",
	],
}
