data = [
	["Area", "NPC", "XP", "Gold Carried", "Pickpocket Skill", "Item Price (base)", "Item Type", "Item"],
	["animtest (Spawned)", "Arundel", 3000, 0, 60, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["animtest (Spawned)", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["animtest (Spawned)", "Frost Giant Guard", 8000, 0, 50, 10, "Axe", "Two-Handed Axe", "Axe_Two-Handed Axe"],
	["animtest (Spawned)", "Frost Giant Guard", 8000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["animtest (Spawned)", "Krilag", 3000, 5, 50, 7, "Scroll", "Note to Krilag", "Scroll_Note to Krilag"],
	["animtest (Spawned)", "Krilag", 3000, 5, 50, 0, "Books & misc", "Krilag's Badge", "Books & misc_Krilag's Badge"],
	["animtest (Spawned)", "Orc", 15, 0, 50, 0, "Gold pieces", "Gold Piece (6)", "Gold pieces_Gold Piece"],
	["animtest (Spawned)", "Orc", 35, 0, 95, 10, "Small sword", "Short Sword ", "Small sword_Short Sword "],
	["animtest (Spawned)", "Orc", 35, 0, 50, 0, "Arrows", "Arrow (10)", "Arrows_Arrow"],
	["animtest (Spawned)", "Orc", 35, 0, 50, 0, "Gold pieces", "Gold Piece (6)", "Gold pieces_Gold Piece"],
	["animtest (Spawned)", "Seer", 15, 0, 80, 15300, "Cloaks & Robes", "Wailing of Virgins", "Cloaks & Robes_Wailing of Virgins"],
	["animtest (Spawned)", "Wyrm Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar1001 - Easthaven (prologue) - Temple of Tempus", "Everard", 5000, 21, 10, 75, "Potion", "Potion of Healing", "Potion_Potion of Healing"],
	["ar1001 - Easthaven (prologue) - Temple of Tempus", "Everard", 5000, 21, 10, 75, "Potion", "Potion of Healing", "Potion_Potion of Healing"],
	["ar1006 - Easthaven (prologue) - Grisella's Winter's Cradle Tavern - main floor", "Hildreth Highhammer", 120, 3, 50, 750, "Potion", "Potion of Frost Giant Strength", "Potion_Potion of Frost Giant Strength"],
	["ar1008 - Easthaven (prologue) - Snowdrift Inn", "Erevain Blacksheaf", 90, 87, 95, 75, "Bow", "Longbow", "Bow_Longbow"],
	["ar1008 - Easthaven (prologue) - Snowdrift Inn", "Erevain Blacksheaf", 90, 87, 50, 0, "Arrows", "Arrow (20)", "Arrows_Arrow"],
	["ar1100 - Easthaven (finale)", "Everard", 5000, 21, 10, 75, "Potion", "Potion of Healing", "Potion_Potion of Healing"],
	["ar1100 - Easthaven (finale)", "Everard", 5000, 21, 10, 75, "Potion", "Potion of Healing", "Potion_Potion of Healing"],
	["ar1101 - Easthaven (finale) - Temple of Tempus/ice tower first floor", "Everard", 5000, 21, 10, 75, "Potion", "Potion of Healing", "Potion_Potion of Healing"],
	["ar1101 - Easthaven (finale) - Temple of Tempus/ice tower first floor", "Everard", 5000, 21, 10, 75, "Potion", "Potion of Healing", "Potion_Potion of Healing"],
	["ar2003 - Kuldahar Pass - Gherg's tower", "Ghereg", 270, 0, 50, 0, "Gold pieces", "Gold Piece (49)", "Gold pieces_Gold Piece"],
	["ar2004 - Kuldahar Pass - Mill - entrance", "Orc", 35, 0, 95, 10, "Small sword", "Short Sword ", "Small sword_Short Sword "],
	["ar2004 - Kuldahar Pass - Mill - entrance", "Orc", 35, 0, 50, 0, "Arrows", "Arrow (10)", "Arrows_Arrow"],
	["ar2004 - Kuldahar Pass - Mill - entrance", "Orc", 35, 0, 50, 0, "Gold pieces", "Gold Piece (6)", "Gold pieces_Gold Piece"],
	["ar2004 - Kuldahar Pass - Mill - entrance", "Orc", 15, 0, 50, 0, "Gold pieces", "Gold Piece (6)", "Gold pieces_Gold Piece"],
	["ar2004 - Kuldahar Pass - Mill - entrance", "Uligar", 35, 55, 10, 200, "Scroll", "Blur", "Scroll_Blur"],
	["ar2004 - Kuldahar Pass - Mill - entrance", "Uligar", 35, 55, 10, 0, "Books & misc", "rndtre26.itm", "Books & misc_rndtre26.itm"],
	["ar2100 (Spawned) - Kuldahar", "Arundel", 3000, 0, 60, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar2101 - Kuldahar - Orrick the Grey's tower - entrance area", "Weenog", 15, 0, 50, 100, "Scroll", "Magic Missile", "Scroll_Magic Missile"],
	["ar2102 - Kuldahar - Orrick the Grey's tower - study", "Orrick the Gray", 4000, 47, 50, 12500, "Wand", "Wand of Paralyzation  (5)", "Wand_Wand of Paralyzation "],
	["ar2102 - Kuldahar - Orrick the Grey's tower - study", "Orrick the Gray", 4000, 47, 60, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar2102 - Kuldahar - Orrick the Grey's tower - study", "Orrick the Gray", 4000, 47, 80, 4000, "Bracers & gauntlets", "Bracers of Defense A.C. 6", "Bracers & gauntlets_Bracers of Defense A.C. 6"],
	["ar2102 - Kuldahar - Orrick the Grey's tower - study", "Orrick the Gray", 4000, 47, 80, 1800, "Amulet", "Amulet of Metaspell Influence", "Amulet_Amulet of Metaspell Influence"],
	["ar2102 - Kuldahar - Orrick the Grey's tower - study", "Orrick the Gray", 4000, 47, 50, 600, "Potion", "Potion of Absorption ", "Potion_Potion of Absorption "],
	["ar2103 (Spawned) - Kuldahar - Conlan's Smithy", "Sheemish", 0, 0, 50, 1, "Key", "Conlan's Key", "Key_Conlan's Key"],
	["ar2108 - Kuldahar - Airship of Oswald Fiddlebender", "Oswald Fiddlebender", 975, 23, 60, 9000, "Ring", "Ring of Protection +2", "Ring_Ring of Protection +2"],
	["ar2108 - Kuldahar - Airship of Oswald Fiddlebender", "Oswald Fiddlebender", 975, 23, 80, 5000, "Amulet", "Necklace of Missiles", "Amulet_Necklace of Missiles"],
	["ar2108 - Kuldahar - Airship of Oswald Fiddlebender", "Oswald Fiddlebender", 975, 23, 80, 1500, "Belt & Girdle", "Golden Girdle", "Belt & Girdle_Golden Girdle"],
	["ar2108 - Kuldahar - Airship of Oswald Fiddlebender", "Oswald Fiddlebender", 975, 23, 50, 500, "Potion", "Oil of Fiery Burning", "Potion_Oil of Fiery Burning"],
	["ar2108 - Kuldahar - Airship of Oswald Fiddlebender", "Oswald Fiddlebender", 975, 23, 10, 500, "Potion", "Oil of Fiery Burning", "Potion_Oil of Fiery Burning"],
	["ar2108 - Kuldahar - Airship of Oswald Fiddlebender", "Oswald Fiddlebender", 975, 23, 10, 500, "Potion", "Oil of Fiery Burning", "Potion_Oil of Fiery Burning"],
	["ar2108 - Kuldahar - Airship of Oswald Fiddlebender", "Oswald Fiddlebender", 975, 23, 50, 450, "Potion", "Potion of Explosions", "Potion_Potion of Explosions"],
	["ar2108 - Kuldahar - Airship of Oswald Fiddlebender", "Oswald Fiddlebender", 975, 23, 50, 400, "Potion", "Potion of Fire Resistance", "Potion_Potion of Fire Resistance"],
	["ar2108 - Kuldahar - Airship of Oswald Fiddlebender", "Oswald Fiddlebender", 975, 23, 10, 250, "Potion", "Potion of Firebreath", "Potion_Potion of Firebreath"],
	["ar2111 - Kuldahar - Root Cellar Tavern", "Whitcomb", 650, 57, 95, 10, "Small sword", "Short Sword ", "Small sword_Short Sword "],
	["ar2111 - Kuldahar - Root Cellar Tavern", "Whitcomb", 650, 57, 50, 0, "Bolts", "Bolt (20)", "Bolts_Bolt"],
	["ar2111 - Kuldahar - Root Cellar Tavern", "Whitcomb", 650, 57, 50, 0, "Bolts", "Bolt (20)", "Bolts_Bolt"],
	["ar2111 - Kuldahar - Root Cellar Tavern", "Whitcomb", 650, 57, 50, 0, "Bolts", "Bolt (20)", "Bolts_Bolt"],
	["ar2112 - Kuldahar - Home of Arundel - first floor", "Arundel", 3000, 0, 60, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar2116 (Spawned) - Kuldahar - Home of Arundel - second floor", "Arundel", 3000, 0, 50, 6750, "Quarterstaff", "Staff of Nature's Wrath +1", "Quarterstaff_Staff of Nature's Wrath +1"],
	["ar3301 - Vale of Shadows - Temple of Myrkul", "Therik", 500, 0, 50, 0, "Books & misc", "rndtre61.itm", "Books & misc_rndtre61.itm"],
	["ar3501 - Vale of Shadows - Tomb of Kresselack - first level", "Mytos", 1000, 0, 95, 1500, "Hammer", "War Hammer +1", "Hammer_War Hammer +1"],
	["ar3501 - Vale of Shadows - Tomb of Kresselack - first level", "Mytos", 1000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar3601 - Temple of the Forgotten God - first level", "Acolyte", 420, 0, 50, 0, "Gold pieces", "Gold Piece (2)", "Gold pieces_Gold Piece"],
	["ar4003 - Dragon's Eye - third dungeon level (Presio)", "Undead Lieutenant", 2000, 0, 60, 25, "Large sword", "Bastard Sword ", "Large sword_Bastard Sword "],
	["ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)", "Albion", 3000, 0, 50, 1, "Key", "Albion's Key", "Key_Albion's Key"],
	["ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)", "Cristiana Knight", 500, 78, 50, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)", "Geelo the Librarian", 2000, 0, 80, 4000, "Bracers & gauntlets", "Bracers of Defense A.C. 6", "Bracers & gauntlets_Bracers of Defense A.C. 6"],
	["ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)", "Geelo the Librarian", 2000, 0, 50, 250, "Potion", "Potion of Invisibility (2)", "Potion_Potion of Invisibility"],
	["ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)", "Iholikan Quinval", 500, 54, 95, 1250, "Large sword", "Long Sword +1", "Large sword_Long Sword +1"],
	["ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)", "Iholikan Quinval", 500, 54, 50, 25, "Arrows", "Arrow of Fire +1 (16)", "Arrows_Arrow of Fire +1"],
	["ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)", "Iholikan Quinval", 500, 54, 50, 18, "Arrows", "Arrow +2 (20)", "Arrows_Arrow +2"],
	["ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)", "Iholikan Quinval", 500, 54, 50, 0, "Arrows", "Arrow (40)", "Arrows_Arrow"],
	["ar4004 - Dragon's Eye - fourth dungeon level (Eldathyn)", "The High Summoner", 1400, 0, 10, 16305, "Quarterstaff", "The Summoner's Staff +3", "Quarterstaff_The Summoner's Staff +3"],
	["ar4005 - Dragon's Eye - fifth dungeon level (Yxunomei)", "The High Torturer", 1400, 0, 50, 1, "Ring", "Ring of Pain Amplification", "Ring_Ring of Pain Amplification"],
	["ar5401 - Severed Hand - Tower of Sheverash - first floor, Kaylessa", "Kaylessa", 1300, 0, 50, 0, "Books & misc", "Piece of broken machinery", "Books & misc_Piece of broken machinery"],
	["ar5401 - Severed Hand - Tower of Sheverash - first floor, Kaylessa", "Kaylessa", 1300, 0, 50, 0, "Books & misc", "rndtre34.itm", "Books & misc_rndtre34.itm"],
	["ar6003 - Dorn's Deep - orog cave, Saablic, Krilag", "Corpse", 0, 0, 50, 1, "Books/Broken shields/bracelets", "Kalabac's Journal", "Books/Broken shields/bracelets_Kalabac's Journal"],
	["ar6003 - Dorn's Deep - orog cave, Saablic, Krilag", "Corpse", 0, 0, 50, 0, "Books & misc", "rndtre53.itm", "Books & misc_rndtre53.itm"],
	["ar6003 - Dorn's Deep - orog cave, Saablic, Krilag", "Krilag", 3000, 5, 50, 7, "Scroll", "Note to Krilag", "Scroll_Note to Krilag"],
	["ar6003 - Dorn's Deep - orog cave, Saablic, Krilag", "Krilag", 3000, 5, 50, 0, "Books & misc", "Krilag's Badge", "Books & misc_Krilag's Badge"],
	["ar6011 - Dorn's Deep - machinery room", "Corpse", 0, 0, 50, 1, "Scroll", "Dver's Note", "Scroll_Dver's Note"],
	["ar7001 - Wyrm's Tooth Glacier - aquarium interior, ice salamander lair", "Frost Salamander", 4000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7001 - Wyrm's Tooth Glacier - aquarium interior, ice salamander lair", "Frost Salamander", 2000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7001 - Wyrm's Tooth Glacier - aquarium interior, ice salamander lair", "Frost Salamander", 3000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7001 - Wyrm's Tooth Glacier - aquarium interior, ice salamander lair", "Greater Ice Troll", 1000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7001 - Wyrm's Tooth Glacier - aquarium interior, ice salamander lair", "Kerish", 5000, 0, 50, 1, "Key", "Dugmaren's Key", "Key_Dugmaren's Key"],
	["ar7001 - Wyrm's Tooth Glacier - aquarium interior, ice salamander lair", "Kerish", 5000, 0, 50, 0, "Books & misc", "rndtre64.itm", "Books & misc_rndtre64.itm"],
	["ar7001 - Wyrm's Tooth Glacier - aquarium interior, ice salamander lair", "Vera", 1400, 0, 95, 3000, "Amulet", "Amulet of Protection +1", "Amulet_Amulet of Protection +1"],
	["ar7001 - Wyrm's Tooth Glacier - aquarium interior, ice salamander lair", "Winter Wolf", 1000, 0, 50, 500, "Fur/pelt", "Winter Wolf Pelt", "Fur/pelt_Winter Wolf Pelt"],
	["ar7003 - Wyrm's Tooth Glacier - Gareth, slaves", "Soth", 15, 0, 50, 4, "Books/Broken shields/bracelets", "Engineering Manual", "Books/Broken shields/bracelets_Engineering Manual"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Frost Giant", 7000, 0, 50, 10, "Axe", "Two-Handed Axe", "Axe_Two-Handed Axe"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Frost Giant", 7000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Frost Giant Guard", 8000, 0, 50, 10, "Axe", "Two-Handed Axe", "Axe_Two-Handed Axe"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Frost Giant Guard", 8000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Frostbite", 7000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Gorg", 8000, 0, 95, 5, "Axe", "Battle Axe", "Axe_Battle Axe"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Gorg", 8000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Joril", 9000, 0, 50, 0, "Books & misc", "Joril's Badge", "Books & misc_Joril's Badge"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Joril", 9000, 0, 50, 0, "Books & misc", "rndtre62.itm", "Books & misc_rndtre62.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Joril", 9000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Joril's Bodyguard", 9000, 0, 50, 10, "Axe", "Two-Handed Axe", "Axe_Two-Handed Axe"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Joril's Bodyguard", 9000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Kontik", 8000, 0, 60, 35000, "Ring", "Kontik's Ring of Wizardry", "Ring_Kontik's Ring of Wizardry"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Kontik", 8000, 0, 60, 9000, "Ring", "Ring of Protection +2", "Ring_Ring of Protection +2"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Kontik", 8000, 0, 50, 0, "Books & misc", "rndtre63.itm", "Books & misc_rndtre63.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Kontik", 8000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "White Wyrm", 5000, 0, 50, 0, "Books & misc", "rndtre66.itm", "Books & misc_rndtre66.itm"],
	["ar7004 - Wyrm's Tooth Glacier - frost giant cave", "Winter Wolf", 1000, 0, 50, 500, "Fur/pelt", "Winter Wolf Pelt", "Fur/pelt_Winter Wolf Pelt"],
	["ar8001 - Lower Dorn's Deep - main cavern", "Fengla", 4, 0, 50, 1, "Key", "Watchtower Key", "Key_Watchtower Key"],
	["ar8001 - Lower Dorn's Deep - main cavern", "Seth", 7000, 93, 155, 20500, "Bracers & gauntlets", "Gauntlets of Elven Might", "Bracers & gauntlets_Gauntlets of Elven Might"],
	["ar8005 - Lower Dorn's Deep - Order of the Kraken garde", "Callard", 420, 0, 10, 7, "Scroll", "Portrait of Marketh", "Scroll_Portrait of Marketh"],
	["ar8006 - Lower Dorn's Deep - Order of the Kraken manor - first floor, Ginafae", "Flozem", 3000, 33, 80, 2900, "Belt & Girdle", "Girdle of Stromnos", "Belt & Girdle_Girdle of Stromnos"],
	["ar8007 (Spawned) - Lower Dorn's Deep - Order of the Kraken manor - second floor, Mekrath", "Flozem", 3000, 33, 80, 2900, "Belt & Girdle", "Girdle of Stromnos", "Belt & Girdle_Girdle of Stromnos"],
	["ar8007 (Spawned) - Lower Dorn's Deep - Order of the Kraken manor - second floor, Mekrath", "Kraken Society Mage", 11000, 50, 80, 4000, "Bracers & gauntlets", "Bracers of Defense A.C. 6", "Bracers & gauntlets_Bracers of Defense A.C. 6"],
	["ar8007 - Lower Dorn's Deep - Order of the Kraken manor - second floor, Mekrath", "Marketh", 8000, 201, 125, 100, "Ring", "Ring of the Gorgon", "Ring_Ring of the Gorgon"],
	["ar8007 - Lower Dorn's Deep - Order of the Kraken manor - second floor, Mekrath", "Marketh", 8000, 201, 125, 0, "Books & misc", "Marketh's Badge", "Books & misc_Marketh's Badge"],
	["ar8007 - Lower Dorn's Deep - Order of the Kraken manor - second floor, Mekrath", "Seth", 7000, 93, 155, 20500, "Bracers & gauntlets", "Gauntlets of Elven Might", "Bracers & gauntlets_Gauntlets of Elven Might"],
	["ar8008 - Lower Dorn's Deep - mines, Guello, Shikata", "Shikata", 5500, 0, 50, 41300, "Spear", "Slayer +5", "Spear_Slayer +5"],
	["ar8010 (Spawned) - Lower Dorn's Deep - Malavon's lair", "Malavon", 50000, 0, 50, 2100, "Scroll", "Malavon's Rage", "Scroll_Malavon's Rage"],
	["ar8010 (Spawned) - Lower Dorn's Deep - Malavon's lair", "Malavon", 50000, 0, 50, 0, "Books & misc", "Malavon's Badge", "Books & misc_Malavon's Badge"],
	["ar8010 - Lower Dorn's Deep - Malavon's lair", "Umber Hulk", 4000, 0, 10, 40, "Books & misc", "Umber Hulk Hide", "Books & misc_Umber Hulk Hide"],
	["ar8011 - Lower Dorn's Deep - forge, Ilmadia", "Maiden Ilmadia", 7000, 85, 50, 1500, "Potion", "Potion of Storm Giant Strength", "Potion_Potion of Storm Giant Strength"],
	["ar8011 - Lower Dorn's Deep - forge, Ilmadia", "Maiden Ilmadia", 7000, 85, 50, 500, "Potion", "Oil of Speed", "Potion_Oil of Speed"],
	["ar8011 - Lower Dorn's Deep - forge, Ilmadia", "Maiden Ilmadia", 7000, 85, 10, 0, "Books & misc", "Maiden Ilmadia's Badge", "Books & misc_Maiden Ilmadia's Badge"],
	["ar8012 - Lower Dorn's Deep - Brother Perdiem", "Brother Perdiem", 1000, 0, 50, 0, "Books & misc", "Brother Perdiem's Badge", "Books & misc_Brother Perdiem's Badge"],
	["ar9100 (Spawned) - Lonelywood", "Alpheus", 4000, 69, 80, 4000, "Bracers & gauntlets", "Bracers of Defense A.C. 6", "Bracers & gauntlets_Bracers of Defense A.C. 6"],
	["ar9100 (Spawned) - Lonelywood", "Alpheus", 4000, 69, 80, 1800, "Amulet", "Amulet of Metaspell Influence", "Amulet_Amulet of Metaspell Influence"],
	["ar9100 (Spawned) - Lonelywood", "Alpheus", 4000, 69, 50, 1250, "Potion", "Potion of Magic Shielding", "Potion_Potion of Magic Shielding"],
	["ar9100 (Spawned) - Lonelywood", "Alpheus", 4000, 69, 50, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9100 (Spawned) - Lonelywood", "Alpheus", 4000, 69, 50, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 65, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 85, 1000, "Cloaks & Robes", "Cloak of Non-Detection", "Cloaks & Robes_Cloak of Non-Detection"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 15, 500, "Potion", "Oil of Speed", "Potion_Oil of Speed"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 55, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 65, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 85, 1000, "Cloaks & Robes", "Cloak of Non-Detection", "Cloaks & Robes_Cloak of Non-Detection"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 15, 500, "Potion", "Oil of Speed", "Potion_Oil of Speed"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 55, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 65, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 85, 1000, "Cloaks & Robes", "Cloak of Non-Detection", "Cloaks & Robes_Cloak of Non-Detection"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 15, 500, "Potion", "Oil of Speed", "Potion_Oil of Speed"],
	["ar9100 (Spawned) - Lonelywood", "Purvis", 11000, 87, 55, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9100 (Spawned) - Lonelywood", "Vaarglan", 8000, 113, 60, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar9100 (Spawned) - Lonelywood", "Vaarglan", 8000, 113, 60, 9000, "Ring", "Ring of Protection +2", "Ring_Ring of Protection +2"],
	["ar9100 (Spawned) - Lonelywood", "Vaarglan", 8000, 113, 80, 4100, "Amulet", "Barrier Amulet", "Amulet_Barrier Amulet"],
	["ar9100 (Spawned) - Lonelywood", "Vaarglan", 8000, 113, 80, 1500, "Belt & Girdle", "Golden Girdle", "Belt & Girdle_Golden Girdle"],
	["ar9100 (Spawned) - Lonelywood", "Vaarglan", 8000, 113, 10, 600, "Scroll", "Emotion, Hope", "Scroll_Emotion, Hope"],
	["ar9100 - Lonelywood", "Rawleigh Gallaway", 650, 0, 50, 75, "Potion", "Potion of Healing", "Potion_Potion of Healing"],
	["ar9101 - Lonelywood - Whistling Gallows - first floor", "Hobart Stubbletoes", 420, 89, 98, 8000, "Crossbow", "Light Crossbow of Speed ", "Crossbow_Light Crossbow of Speed "],
	["ar9101 - Lonelywood - Whistling Gallows - first floor", "Hobart Stubbletoes", 420, 89, 83, 7000, "Bracers & gauntlets", "Gauntlets of Dexterity", "Bracers & gauntlets_Gauntlets of Dexterity"],
	["ar9101 - Lonelywood - Whistling Gallows - first floor", "Hobart Stubbletoes", 420, 89, 53, 0, "Bolts", "Bolt (20)", "Bolts_Bolt"],
	["ar9101 - Lonelywood - Whistling Gallows - first floor", "Kieran Nye", 4000, 54, 60, 5000, "Ring", "Ring of Greater Resistance", "Ring_Ring of Greater Resistance"],
	["ar9101 - Lonelywood - Whistling Gallows - first floor", "Kieran Nye", 4000, 54, 50, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9103 - Lonelywood - Temple of Waukeen", "Quinn Silverfinger", 2000, 100, 95, 8500, "Morning star", "Morning Star +4: Defender", "Morning star_Morning Star +4: Defender"],
	["ar9103 - Lonelywood - Temple of Waukeen", "Quinn Silverfinger", 2000, 100, 50, 800, "Bullets", "Force Bullet +2 (40)", "Bullets_Force Bullet +2"],
	["ar9104 - Lonelywood - Home of Emmerich", "Emmerich Hawk", 1400, 100, 80, 5000, "Bracers & gauntlets", "Bracers of Archery", "Bracers & gauntlets_Bracers of Archery"],
	["ar9104 - Lonelywood - Home of Emmerich", "Emmerich Hawk", 1400, 100, 50, 1000, "Arrows", "Inferno Arrow +2 (20)", "Arrows_Inferno Arrow +2"],
	["ar9104 - Lonelywood - Home of Emmerich", "Emmerich Hawk", 1400, 100, 80, 1000, "Cloaks & Robes", "Shadowed Cloak", "Cloaks & Robes_Shadowed Cloak"],
	["ar9104 - Lonelywood - Home of Emmerich", "Emmerich Hawk", 1400, 100, 50, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9104 - Lonelywood - Home of Emmerich", "Emmerich Hawk", 1400, 100, 50, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9104 - Lonelywood - Home of Emmerich", "Emmerich Hawk", 1400, 100, 50, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9104 - Lonelywood - Home of Emmerich", "Emmerich Hawk", 1400, 100, 95, 200, "Large sword", "Finest Long Sword", "Large sword_Finest Long Sword"],
	["ar9104 - Lonelywood - Home of Emmerich", "Emmerich Hawk", 1400, 100, 50, 200, "Arrows", "Confusion Arrow +3 (20)", "Arrows_Confusion Arrow +3"],
	["ar9104 - Lonelywood - Home of Emmerich", "Emmerich Hawk", 1400, 100, 50, 50, "Arrows", "Arrow of Piercing +3 (20)", "Arrows_Arrow of Piercing +3"],
	["ar9106 (Spawned) - Lonelywood - Thurlow home - first floor", "Purvis", 11000, 87, 65, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar9106 (Spawned) - Lonelywood - Thurlow home - first floor", "Purvis", 11000, 87, 85, 1000, "Cloaks & Robes", "Cloak of Non-Detection", "Cloaks & Robes_Cloak of Non-Detection"],
	["ar9106 (Spawned) - Lonelywood - Thurlow home - first floor", "Purvis", 11000, 87, 15, 500, "Potion", "Oil of Speed", "Potion_Oil of Speed"],
	["ar9106 (Spawned) - Lonelywood - Thurlow home - first floor", "Purvis", 11000, 87, 55, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9107 (Spawned) - Lonelywood - Thurlow home - second floor", "Purvis", 11000, 87, 65, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar9107 (Spawned) - Lonelywood - Thurlow home - second floor", "Purvis", 11000, 87, 85, 1000, "Cloaks & Robes", "Cloak of Non-Detection", "Cloaks & Robes_Cloak of Non-Detection"],
	["ar9107 (Spawned) - Lonelywood - Thurlow home - second floor", "Purvis", 11000, 87, 15, 500, "Potion", "Oil of Speed", "Potion_Oil of Speed"],
	["ar9107 (Spawned) - Lonelywood - Thurlow home - second floor", "Purvis", 11000, 87, 55, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9110 - Lonelywood - Home of Purvis", "Purvis", 11000, 87, 65, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar9110 - Lonelywood - Home of Purvis", "Purvis", 11000, 87, 85, 1000, "Cloaks & Robes", "Cloak of Non-Detection", "Cloaks & Robes_Cloak of Non-Detection"],
	["ar9110 - Lonelywood - Home of Purvis", "Purvis", 11000, 87, 55, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9200 - Barbarian camp", "Bear Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (3)", "Potion_Flaming Oil"],
	["ar9200 - Barbarian camp", "Bear Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9200 - Barbarian camp", "Bear Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (2)", "Potion_Flaming Oil"],
	["ar9200 - Barbarian camp", "Bear Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9200 - Barbarian camp", "Bear Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil", "Potion_Flaming Oil"],
	["ar9200 - Barbarian camp", "Bear Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9200 - Barbarian camp", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9200 - Barbarian camp", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9200 - Barbarian camp", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9200 - Barbarian camp", "Wyrm Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9200 - Barbarian camp", "Wyrm Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9200 - Barbarian camp", "Wyrm Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9201 (Spawned) - Barbarian camp - Mead Hall", "Seer", 15, 0, 80, 15300, "Cloaks & Robes", "Wailing of Virgins", "Cloaks & Robes_Wailing of Virgins"],
	["ar9201 (Spawned) - Barbarian camp - Mead Hall", "Seer", 15, 0, 80, 15300, "Cloaks & Robes", "Wailing of Virgins", "Cloaks & Robes_Wailing of Virgins"],
	["ar9201 - Barbarian camp - Mead Hall", "Bear Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (3)", "Potion_Flaming Oil"],
	["ar9201 - Barbarian camp - Mead Hall", "Bear Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9201 - Barbarian camp - Mead Hall", "Bear Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (2)", "Potion_Flaming Oil"],
	["ar9201 - Barbarian camp - Mead Hall", "Bear Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9201 - Barbarian camp - Mead Hall", "Bear Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil", "Potion_Flaming Oil"],
	["ar9201 - Barbarian camp - Mead Hall", "Bear Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9201 - Barbarian camp - Mead Hall", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9201 - Barbarian camp - Mead Hall", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9201 - Barbarian camp - Mead Hall", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9201 - Barbarian camp - Mead Hall", "Seer", 15, 0, 80, 15300, "Cloaks & Robes", "Wailing of Virgins", "Cloaks & Robes_Wailing of Virgins"],
	["ar9201 - Barbarian camp - Mead Hall", "Wyrm Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9201 - Barbarian camp - Mead Hall", "Wyrm Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9201 - Barbarian camp - Mead Hall", "Wyrm Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9501 - Gloomfrost interior - first level, Tiernon", "Tiernon", 975, 0, 10, 1750, "Books & misc", "Tiernon's Hearthstone", "Books & misc_Tiernon's Hearthstone"],
	["ar9501 - Gloomfrost interior - first level, Tiernon", "Tiernon", 975, 0, 50, 1, "Books & misc", "Mirror of Black Ice", "Books & misc_Mirror of Black Ice"],
	["ar9502 - Gloomfrost interior - second level, Seer", "Seer", 15, 0, 80, 15300, "Cloaks & Robes", "Wailing of Virgins", "Cloaks & Robes_Wailing of Virgins"],
	["ar9600 - Sea of Moving Ice", "Bear Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (4)", "Potion_Flaming Oil"],
	["ar9600 - Sea of Moving Ice", "Bear Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9600 - Sea of Moving Ice", "Bear Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (4)", "Potion_Flaming Oil"],
	["ar9600 - Sea of Moving Ice", "Bear Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9600 - Sea of Moving Ice", "Bear Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (4)", "Potion_Flaming Oil"],
	["ar9600 - Sea of Moving Ice", "Bear Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9600 - Sea of Moving Ice", "Elk Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (4)", "Potion_Flaming Oil"],
	["ar9600 - Sea of Moving Ice", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9600 - Sea of Moving Ice", "Elk Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (4)", "Potion_Flaming Oil"],
	["ar9600 - Sea of Moving Ice", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9600 - Sea of Moving Ice", "Elk Tribe Warrior", 4000, 0, 95, 300, "Potion", "Flaming Oil (4)", "Potion_Flaming Oil"],
	["ar9600 - Sea of Moving Ice", "Elk Tribe Warrior", 4000, 0, 50, 0, "Books & misc", "rndtre81.itm", "Books & misc_rndtre81.itm"],
	["ar9602 - Sea of Moving Ice - Field of Bones", "Boneguard Skeleton", 4000, 0, 50, 0, "Books & misc", "rndtre85.itm", "Books & misc_rndtre85.itm"],
	["ar9602 - Sea of Moving Ice - Field of Bones", "Xactile", 6000, 0, 50, 1500, "Mace & Club", "Mace +1", "Mace & Club_Mace +1"],
	["ar9700 - Anauroch Castle - outer courtyard (TotL start area)", "Hobart Stubbletoes", 420, 89, 98, 8000, "Crossbow", "Light Crossbow of Speed ", "Crossbow_Light Crossbow of Speed "],
	["ar9700 - Anauroch Castle - outer courtyard (TotL start area)", "Hobart Stubbletoes", 420, 89, 83, 7000, "Bracers & gauntlets", "Gauntlets of Dexterity", "Bracers & gauntlets_Gauntlets of Dexterity"],
	["ar9700 - Anauroch Castle - outer courtyard (TotL start area)", "Hobart Stubbletoes", 420, 89, 53, 0, "Bolts", "Bolt (20)", "Bolts_Bolt"],
	["ar9704 - Anauroch Castle - west Tower upstairs - Harald", "Harald", 6000, 91, 60, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar9704 - Anauroch Castle - west Tower upstairs - Harald", "Harald", 6000, 91, 80, 6000, "Bracers & gauntlets", "Gauntlets of Weapon Expertise", "Bracers & gauntlets_Gauntlets of Weapon Expertise"],
	["ar9704 - Anauroch Castle - west Tower upstairs - Harald", "Harald", 6000, 91, 80, 1500, "Belt & Girdle", "Golden Girdle", "Belt & Girdle_Golden Girdle"],
	["ar9706 - Anauroch Castle - north Tower upstairs - harpy queen", "Harpy Queen", 7000, 0, 60, 5000, "Ring", "Ring of Greater Resistance", "Ring_Ring of Greater Resistance"],
	["ar9706 - Anauroch Castle - north Tower upstairs - harpy queen", "Harpy Queen", 7000, 0, 50, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9706 - Anauroch Castle - north Tower upstairs - harpy queen", "Harpy Queen", 7000, 0, 50, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9706 - Anauroch Castle - north Tower upstairs - harpy queen", "Harpy Queen", 7000, 0, 10, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Adran Runeshadow", 6000, 1230, 50, 22000, "Wand", "Wand of Fire (10)", "Wand_Wand of Fire"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Adran Runeshadow", 6000, 1230, 80, 10000, "Cloaks & Robes", "Cloak of Scintillating Colors", "Cloaks & Robes_Cloak of Scintillating Colors"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Adran Runeshadow", 6000, 1230, 60, 9000, "Ring", "Ring of Protection +2", "Ring_Ring of Protection +2"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Adran Runeshadow", 6000, 1230, 60, 1500, "Ring", "Ring of Fire Resistance", "Ring_Ring of Fire Resistance"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Adran Runeshadow", 6000, 1230, 80, 1500, "Belt & Girdle", "Golden Girdle", "Belt & Girdle_Golden Girdle"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Adran Runeshadow", 6000, 1230, 50, 0, "Drinks (IWD)", "The Genie's Flask", "Drinks (IWD)_The Genie's Flask"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Criek of Bane", 7000, 231, 60, 5000, "Ring", "Ring of Greater Resistance", "Ring_Ring of Greater Resistance"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Criek of Bane", 7000, 231, 50, 5000, "Containers/eye/broken armor", "Bag of Holding", "Containers/eye/broken armor_Bag of Holding"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Shelhai", 7000, 800, 60, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Shelhai", 7000, 800, 80, 9000, "Bracers & gauntlets", "Gauntlets of Ogre Power", "Bracers & gauntlets_Gauntlets of Ogre Power"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Shelhai", 7000, 800, 50, 4000, "Gem", "King's Tears (7)", "Gem_King's Tears"],
	["ar9708 - Anauroch Castle - east Tower upstairs - Banites", "Shelhai", 7000, 800, 60, 500, "Ring", "Fire Opal Ring", "Ring_Fire Opal Ring"],
	["ar9715 - Anauroch Castle - hideout of Hobart", "Hobart Stubbletoes", 420, 89, 98, 8000, "Crossbow", "Light Crossbow of Speed ", "Crossbow_Light Crossbow of Speed "],
	["ar9715 - Anauroch Castle - hideout of Hobart", "Hobart Stubbletoes", 420, 89, 83, 7000, "Bracers & gauntlets", "Gauntlets of Dexterity", "Bracers & gauntlets_Gauntlets of Dexterity"],
	["ar9715 - Anauroch Castle - hideout of Hobart", "Hobart Stubbletoes", 420, 89, 53, 0, "Bolts", "Bolt (20)", "Bolts_Bolt"],
	["unknown", "Adran Runeshadow (animtest)", 6000, 1230, 50, 22000, "Wand", "Wand of Fire (10)", "Wand_Wand of Fire"],
	["unknown", "Adran Runeshadow (animtest)", 6000, 1230, 80, 10000, "Cloaks & Robes", "Cloak of Scintillating Colors", "Cloaks & Robes_Cloak of Scintillating Colors"],
	["unknown", "Adran Runeshadow (animtest)", 6000, 1230, 60, 9000, "Ring", "Ring of Protection +2", "Ring_Ring of Protection +2"],
	["unknown", "Adran Runeshadow (animtest)", 6000, 1230, 60, 1500, "Ring", "Ring of Fire Resistance", "Ring_Ring of Fire Resistance"],
	["unknown", "Adran Runeshadow (animtest)", 6000, 1230, 80, 1500, "Belt & Girdle", "Golden Girdle", "Belt & Girdle_Golden Girdle"],
	["unknown", "Adran Runeshadow (animtest)", 6000, 1230, 50, 0, "Drinks (IWD)", "The Genie's Flask", "Drinks (IWD)_The Genie's Flask"],
	["unknown", "Baern (hparty02)", 0, 0, 60, 3500, "Ring", "Ring of the Protector +2", "Ring_Ring of the Protector +2"],
	["unknown", "Baern (hparty02)", 0, 0, 50, 250, "Potion", "Elixir of Health (3)", "Potion_Elixir of Health"],
	["unknown", "Baern (hparty02)", 0, 0, 50, 100, "Potion", "Antidote (3)", "Potion_Antidote"],
	["unknown", "Baern (hparty02)", 0, 0, 50, 75, "Potion", "Potion of Healing (3)", "Potion_Potion of Healing"],
	["unknown", "Cadriel (hparty03)", 0, 0, 50, 450, "Potion", "Potion of Extra Healing (3)", "Potion_Potion of Extra Healing"],
	["unknown", "Cadriel (hparty03)", 0, 0, 50, 75, "Potion", "Potion of Healing (3)", "Potion_Potion of Healing"],
	["unknown", "Felicia (hparty06)", 0, 0, 130, 8000, "Books & misc", "Bardic Horn of Valhalla", "Books & misc_Bardic Horn of Valhalla"],
	["unknown", "Felicia (hparty06)", 0, 0, 130, 75, "Potion", "Potion of Healing (2)", "Potion_Potion of Healing"],
	["unknown", "Gorris (hparty01)", 0, 0, 60, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["unknown", "Gorris (hparty01)", 0, 0, 80, 4000, "Bracers & gauntlets", "Gauntlets of Weapon Skill", "Bracers & gauntlets_Gauntlets of Weapon Skill"],
	["unknown", "Gorris (hparty01)", 0, 0, 80, 4000, "Amulet", "Black Wolf Talisman", "Amulet_Black Wolf Talisman"],
	["unknown", "Gorris (hparty01)", 0, 0, 80, 1500, "Belt & Girdle", "Girdle of Bluntness", "Belt & Girdle_Girdle of Bluntness"],
	["unknown", "Gorris (hparty01)", 0, 0, 50, 1000, "Potion", "Potion of Fire Giant Strength", "Potion_Potion of Fire Giant Strength"],
	["unknown", "Gorris (hparty01)", 0, 0, 50, 450, "Potion", "Potion of Extra Healing (3)", "Potion_Potion of Extra Healing"],
	["unknown", "Gorris (hparty01)", 0, 0, 50, 75, "Potion", "Potion of Healing (3)", "Potion_Potion of Healing"],
	["unknown", "Hobart Stubbletoes (hobarth)", 420, 89, 98, 8000, "Crossbow", "Light Crossbow of Speed ", "Crossbow_Light Crossbow of Speed "],
	["unknown", "Hobart Stubbletoes (hobarth)", 420, 89, 83, 7000, "Bracers & gauntlets", "Gauntlets of Dexterity", "Bracers & gauntlets_Gauntlets of Dexterity"],
	["unknown", "Hobart Stubbletoes (hobarth)", 420, 89, 53, 0, "Bolts", "Bolt (20)", "Bolts_Bolt"],
	["unknown", "Ilauna (hparty05)", 0, 0, 80, 9000, "Cloaks & Robes", "Cloak of Protection +2", "Cloaks & Robes_Cloak of Protection +2"],
	["unknown", "Ilauna (hparty05)", 0, 0, 80, 1800, "Amulet", "Amulet of Metaspell Influence", "Amulet_Amulet of Metaspell Influence"],
	["unknown", "Ilauna (hparty05)", 0, 0, 50, 75, "Potion", "Potion of Healing (2)", "Potion_Potion of Healing"],
	["unknown", "Kirika (hparty04)", 0, 0, 80, 12000, "Bracers & gauntlets", "Kaylessa's Gloves", "Bracers & gauntlets_Kaylessa's Gloves"],
	["unknown", "Kirika (hparty04)", 0, 0, 60, 11450, "Ring", "Ring of Shadows", "Ring_Ring of Shadows"],
	["unknown", "Kirika (hparty04)", 0, 0, 95, 3000, "Crossbow", "Light Crossbow of Speed +2", "Crossbow_Light Crossbow of Speed +2"],
	["unknown", "Kirika (hparty04)", 0, 0, 50, 400, "Potion", "Potion of Master Thievery", "Potion_Potion of Master Thievery"],
	["unknown", "Kirika (hparty04)", 0, 0, 50, 250, "Potion", "Potion of Invisibility", "Potion_Potion of Invisibility"],
	["unknown", "Kirika (hparty04)", 0, 0, 50, 75, "Bolts", "Bolt of Biting +1 (29)", "Bolts_Bolt of Biting +1"],
	["unknown", "Kirika (hparty04)", 0, 0, 50, 75, "Potion", "Potion of Healing (2)", "Potion_Potion of Healing"],
	["unknown", "Kirika (hparty04)", 0, 0, 50, 30, "Bolts", "Bolt of Lightning +1 (20)", "Bolts_Bolt of Lightning +1"],
	["unknown", "Kirika (hparty04)", 0, 0, 50, 10, "Bolts", "Bolt +1 (40)", "Bolts_Bolt +1"],
	["unknown", "Purvis (purvish)", 11000, 87, 65, 10000, "Ring", "Ring of Free Action", "Ring_Ring of Free Action"],
	["unknown", "Purvis (purvish)", 11000, 87, 85, 1000, "Cloaks & Robes", "Cloak of Non-Detection", "Cloaks & Robes_Cloak of Non-Detection"],
	["unknown", "Purvis (purvish)", 11000, 87, 15, 500, "Potion", "Oil of Speed", "Potion_Oil of Speed"],
	["unknown", "Purvis (purvish)", 11000, 87, 55, 300, "Potion", "Potion of Extra Healing", "Potion_Potion of Extra Healing"],
]
